### ISSUE TITLE
Pending update for uno panel that I don't have

### ISSUE THREAD

**Issue by sheyman1** [ufodone/envisalink_new#102]
Great work on this integration, really appreciate all the work you've put into this.  Just a quick question, is there any way to get rid of the pending update showing in HACS.  I have a Honeywell panel running v0.8.2 and the update v0.9.0 keeps showing up but in the description it says do not install this if you have a Honeywell panel.  Thanks again for everything you've done on this!!!

**Comment by ufodone** [comment]
You probably have the "Show Beta Versions" box checked for the integration.  If you turn that off, it should make the notification go away.  You can access that via HACS->Envisalink Refactored and then the Redownload item after clicking the three dots in top right corner.

**Comment by sheyman1** [comment]
Thank you, that did the trick.  Thanks for all you have done on this, works
beautifully with my Vista 20p.
