### ISSUE TITLE
Install steps for existing envisalink user

### ISSUE THREAD

**Issue by NukeThemTillTheyGlow** [ufodone/envisalink_new#107]
Just so I understand this correctly and the integration picks up the existing configuration details properly, is this the correct sequence of events to get the envisalink_new integration installed, configured and running?

1. Install via HACS per instructions, but do not reboot
2. rename existing envisalink heading to envislink_new
3. Reboot HA
4. Confirm integration and entities are created and working, including unique ids
5. edit config yaml, comment out or delete all entities/zones from original integration
6. reboot
7. Confirm its all working
Did I miss anything?  Or should I remove the old integration, device, edit yaml and reboot first to completely get rid of original envisalink integration and start clean?

**Comment by ufodone** [comment]
That sequence should work.  Renaming the envisalink config in configuration.yaml will just allow `envisalink_new` to pick up your same config - it's just a convenience to avoid you needing to manually set things up again. You should not need to remove any old `envisalink` setup with this approach.

**Comment by NukeThemTillTheyGlow** [comment]
> That sequence should work. Renaming the envisalink config in configuration.yaml will just allow `envisalink_new` to pick up your same config - it's just a convenience to avoid you needing to manually set things up again. You should not need to remove any old `envisalink` setup with this approach.

Ok, thanks for confirming.  So I can skip step 5 and just leave the original code in there under the new name?  If I understand how this differs from the original integration, once it reads the config data from the old and sets up the device and entries (or I manually input them), then the envisalink_new section int he yaml isn't needed?

**Comment by ufodone** [comment]
On HA startup, if the config is present in configuration.yaml, it will re-sync it into the config entry which means that any changes you have made via the UI could get overwritten.

For this reason, it's best to remove the config from configuration.yaml once it has been imported and is working correctly and then make any subsequent changes via the UI.

**Comment by NukeThemTillTheyGlow** [comment]
I installed _new and its up and working.  I just renamed original integration to envisalink_new, installed and rebooted.  

Some interesting observations

1. "Envisalink_new" appears under settings/devices & services/integrations as 1 device.  When I click on integration I see one partition, 1 device, 49 entities.  Original envisalink integration had two devices (two partitions, 01 and 02), 15 zones (see original conf.yaml entries below).  Envisalink UI shows 2 partitions, 16 zones.
2. When I click on the 1 device link under the integartion I get an error message "Error while loading page devices"  no other details
3. When I click on the 49 entities, I get what appears to be two entities per original config zones (see yaml below)...   1) binary_sensor.zone_name and 2) binary_sensor.zone_name_fault
4. Some of the entities are junk, like Empty & empty_fault..  I guess just remove them from the integration page or out of the yaml?
5. I also get 9 other binary_sensor, alarm_control_panel, sensor and switch entities for each partitiion, 1 and 3, total of 18.  

envisalink_new:
  host: 192.168.1.xx
  panel_type: DSC
  user_name: xxxx
  password: xxxxx
  code: "xxxx"
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  timeout: 10
  panic_type: Police
  zones:
    1:
      name: "Empty"
      type: "opening"
    2:
      name: "CO Detect Upstairs"
      type: "carbon_monoxide"
    3:
      name: "CO Detect Basement"
      type: "carbon_monoxide"
    4:
      name: "Exercise Room Glassbreak"
      type: "tamper"
    5:
      name: "Office Glassbreak"
      type: "tamper"
    6:
      name: "Abiageal Bedroom Glassbreak"
      type: "tamper"
    7:
      name: "Garage Entrance Door"
      type: "door"
    8:
      name: "Service Door"
      type: "door"
    9:
      name: "Breakfast Room Door"
      type: "door"
    10:
      name: "Front Door"
      type: "door"
    11:
      name: "Basement Door"
      type: "door"
    12:
      name: "Garage Side Door"
      type: "door"
    13:
      name: "Foyer Motion"
      type: "motion"
    14:
      name: "Family Room Motion"
      type: "motion"
    15:
      name: "Basement Motion"
      type: "Motion"
    16:
      name: "Office motion"
      type: "motion"
  partitions:
    1:
      name: "Partition 01"
    3:
      name: "Partition 03"

**Comment by NukeThemTillTheyGlow** [comment]
> On HA startup, if the config is present in configuration.yaml, it will re-sync it into the config entry which means that any changes you have made via the UI could get overwritten.
> 
> For this reason, it's best to remove the config from configuration.yaml once it has been imported and is working correctly and then make any subsequent changes via the UI.

ahhh gotcha, now I get it, thanks!!  I just finished dinner and typing in the results of my initial install, I will remove everything from config yaml and reboot.

**Comment by NukeThemTillTheyGlow** [comment]
> > On HA startup, if the config is present in configuration.yaml, it will re-sync it into the config entry which means that any changes you have made via the UI could get overwritten.
> > For this reason, it's best to remove the config from configuration.yaml once it has been imported and is working correctly and then make any subsequent changes via the UI.
> 
> ahhh gotcha, now I get it, thanks!! I just finished dinner and typing in the results of my initial install, I will remove everything from config yaml and reboot.

I removed all envisalink entries from configuration.yaml and its all good, same 49 entities, but still error on device.  I checked all of the config options and then flipped on "create zone bypass switches" and now I have 65 entities.  Very cool.

I need to confirm with the Envisalink people while I'm getting two partitions, my system is not partitioned (that I am aware of).  I do have one DSC expansion card.

**Comment by ufodone** [comment]
> I need to confirm with the Envisalink people while I'm getting two partitions

Your configuration indicated you had two partitions (01 and 03).  But you also said that the original integration had partitions 1 and 2 but `envisalink_new` was just showing one partition.  So I'm a bit confused as to what you are seeing now and what you expect to see.

>When I click on the 1 device link under the integartion I get an error message "Error while loading page devices" no other details

Does that page show anything or just the error?  I've not seen that message before.  Could you enable debug logging on `envisalink_new` and try to reproduce the issue?  That might provide a clue.

> Some of the entities are junk, like Empty & empty_fault

Those specific example are just the entities representing zone 1 from your configuration which you've named "Empty".  If zone 1 is not actually used by you system, you can go into the UI configuration and adjust the zone list to omit it.  Based on the config you posted about, you could change the zone list to "2-16" (I suspect it's 1-16 right now).

**Comment by NukeThemTillTheyGlow** [comment]
> > I need to confirm with the Envisalink people while I'm getting two partitions
> 
> Your configuration indicated you had two partitions (01 and 03). But you also said that the original integration had partitions 1 and 2 but `envisalink_new` was just showing one partition. So I'm a bit confused as to what you are seeing now and what you expect to see.
> 
> > When I click on the 1 device link under the integartion I get an error message "Error while loading page devices" no other details
> 
> Does that page show anything or just the error? I've not seen that message before. Could you enable debug logging on `envisalink_new` and try to reproduce the issue? That might provide a clue.
> 
> > Some of the entities are junk, like Empty & empty_fault
> 
> Those specific example are just the entities representing zone 1 from your configuration which you've named "Empty". If zone 1 is not actually used by you system, you can go into the UI configuration and adjust the zone list to omit it. Based on the config you posted about, you could change the zone list to "2-16" (I suspect it's 1-16 right now).

Sorry about the late response.  With "envisalink_new" integration there is one Device called "Partition 01".  In Setting/Devices & services/EyezOn there is one device and 70 entities.  Clicking on Device results in a large list under Controls including entiries for Partition 01 and 03, both disarmed at the moment.  Senors has all of my sensors as well as some Partition 03 entities too.  Same for 3rd section called Diagnostic.  

Now I looked under Configure under the main integration page and there are some interesting entries.   Under Basic, I see in Partition List "1,3".  Zone list is "1-16"".    Everything looks fine under Advanced.  Under Partition Assignments there are two open fields, Partition 1 and 3, nothing in them.

I assume it generates Partition 3 either from the setting in Basic/Partition List...or from the fact there is an expansion board?
