### ISSUE TITLE
Is it possible to pull the battery state / low battery warning for wireless sensors on a Honeywell panel? 

### ISSUE THREAD

**Issue by Hamish1066** [ufodone/envisalink_new#109]

**Comment by Hamish1066** [comment]
The documentation states that this is possible for DSC systems, but is silent on Honeywell systems. I've seen reports on Reddit that it is possible with Honeywell systems, but would like confirmation before I upgrade as this is the sole reason I would upgrade. If it is possible, can I identify which sensor has a low battery state?

**Comment by ufodone** [comment]
No, this integration does not support battery state on wireless sensors for Honeywell systems.  To my knowledge, this is not exposed through the interface that the Envisalink boards provide so there isn't a way that I could expose it in the integration.

**Comment by Hamish1066** [comment]
Thanks for your response.
