### ISSUE TITLE
"arm night" via HA arms the panel in stay/home mode

### ISSUE THREAD

**Issue by jonoberheide** [ufodone/envisalink_new#114]
When clicking the "Arm Night" button in HA, the keypad shows and announces that it is in "Arm Stay" mode. HA updates the state and shows it as Armed Home.

However, when clicking the "Arm Night" button on the Honeywell keypad, it properly goes into "Arm Stay Instant" mode (which Night mode is configured on my keypad as Instant). HA updates the state and shows it as Armed Night.

The same occurs if I invoke things through the Envisalink web portal. Arm Night via the portal puts it in Arm Stay mode and HA shows it as Armed Home. Arm Instant via the portal puts it in Armed Stay Instant and HA shows it as Armed Night.

It's like HA and/or the Envisalink is sending the wrong command for Arm Night?

This is a Honeywell VISTA panel with Envisalink 4.

**Comment by jonoberheide** [comment]
Ok, looking at the code now...

It looks like there should be some configuration option to select what to send for the Arm Night action?

![image](https://github.com/ufodone/envisalink_new/assets/506986/277593db-f24c-4892-8b05-5cd30989d9a1)

However, I don't see that in my Advanced config UI for some reason...

![image](https://github.com/ufodone/envisalink_new/assets/506986/4d5e4164-3e96-4063-a375-86e7cf663e6b)

**Comment by jonoberheide** [comment]
If I "if True:" that panel type check, the config option shows up, I can select "Instant" and everything magically works as expected.

Now, I suppose this issue is more of a "why in the world isn't my panel type set to Honeywell and where would one even find that?"

**Comment by ufodone** [comment]
Hi, I've been seeing some cases where the panel type is set incorrectly but haven't yet figured out how that is happening.  I'm guessing it has something do when when the EVL device is initially added and something goes wrong with the detection.

If you're comfortable doing it, you could "fix" the problem by manually editing the `panel_type` attribute in the `envisalink_new` section in `.storage/core.config_entries` and then restart HA.

But I do need to get to the bottom of how this is happening.  If you remember, can you describe how you setup `envisalink_new` initially and if there were any hiccups along the way?

**Comment by jonoberheide** [comment]
panel_type is indeed null in the config, despite HONEYWELL showing up in the device info. I will override it manually.

![image](https://github.com/ufodone/envisalink_new/assets/506986/34255a6a-3659-423b-aaaa-431141b73f22)

Also, happy to test/run any panel auto-detection code if it's helpful.

My install was probably 6 months ago. Never used the old integration, just envisalink_new. I think it was pretty vanilla and I don't ever recall seeing the additional Night options in Advanced so maybe it just missed the panel type in the original initialization?

**Comment by jonoberheide** [comment]
I'm not super familiar with the code base, but I can't seem to find a place where the code (assuming a fresh install with no existing YAML config) actually sets the panel type in the config?

**Comment by ufodone** [comment]
The panel type is set in the `_validate_input` function in ConfigFlow.  I haven't been able to reproduce getting a null entry but my suspicion is that it may have been related to a version when the 4MAX wasn't being properly detected.  Both issues I've seen recently have been on 4MAX panels.

I've published a new v0.9.1 release which attempts to detect and correct a bad config entry.

**Comment by jonoberheide** [comment]
👍
