### ISSUE TITLE
HA wouldn't complete the restart after upgrade to 0.4.1

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#12]
@ChirpyTurnip wrote:

>I tried to update to the new version (DSV/EVL4) and HA wouldn't complete
the restart. I removed the integration and re-added and it refuses to
connect to the EVL. I've rolled back to v3.5, and it connected immediately.
Unfortunately all my zone names etc are missing so the entities names are
different now from the looks of it so I will need to unpick a few things....
>
>Any tests you want me to run?

**Comment by ufodone** [comment]
Do you have the logs from when HA wouldn't restart?  Or when it was unable to connect?

Did you have your config defined in configuration.yaml?

When you say the entity names were different, do you mean different than what was defined in configuration.yaml?  Or were you not using configuration.yaml to bootstrap your device?  If the latter, then it's possible this release may have changed the naming to comply with HA standards.

**Comment by ChirpyTurnip** [comment]
It just hung on the starting services bit "Starting Envisalink...." and then nothing.....as soon as I deleted the integration HA completed loading. I then added it again (v0.4.1) but it wouldn't connect to the EVL, it just said "unknown error occurred". Re-loaded v0.3.5, went through the wizard and everything connected instantly. 

However, yes, zone names etc have all changed. Everything now in the form: "binary_sensor.home_alarm_zone_1" - previously these had names based on what was in the yaml config (e.g. "binary_sensor.home_alarm_laundry"). Deleting the envisalink integration, re-enabling the old yaml config, and then restarting HA, got it to pick up everything again. 

But, that still leaves the v0.4.1 question.....how to tackle?

**Comment by ChirpyTurnip** [comment]
I did look in the log for errors btw, and searched for Envisalink, but found nothing other than the warning that a non standard integration was present (the standard opening messages for all integrations)....but nothing else...

**Comment by ufodone** [comment]
So, generally speaking, I would recommend leaving your config in configuration.yaml (but renaming to `envisalink_new:`.  That will ensure that the entity naming is preserved.  Without it, HA has now way to know what to name the entities if you remove the integration or delete and re-add the device and so it falls back to default naming.  It's fine to leave the configuration in place even after it has imported it.  However, be aware that whenever you start/restart HA, it will compare what's in configuration.yaml with the config entry and re-import any changes.  This will work fine as long as you don't make changes via the UI.

Now, to your upgrading problem.  When you say you removed the integration, was that via HACS or did you just delete the device from Settings->Configuration & Services? 

Are you running the stock `envisalink` integration right now or 0.3.5 of `envisalink_new`?  I think from your comments that it's the stock one.  If so, here's what I'd recommend to get to 0.4.1:

1. If you still have `envisalink_new` installed via HACS, then remove it and restart.
2. Re-install envisalink_new via HACS (0.4.1 version)
4. Rename you `envisalink:` to `envisalink_new:` in configuration.yaml
5. Restart HA

Theoretically it should now import your config on startup and you should be good to go.

**Comment by ChirpyTurnip** [comment]
So:

On YAML:
Yes - renamed old envisalink config to envisalink_new. Once the initial migration was completed commented out this line (it's an include statement to a separate yaml file). 

For the upgrade to 0.4.1:

1. Initially tried a standard via-HACS update + restart - that hung
2. Remove integration via services, restarted, re-added integration via services, followed wizard to connect to  alarm ip address and this failed.
3. Removed, rolled back to 3.5, wizard etc all works fine, but with nothing old to import names revert to defaults. 
4. Removed integration via services, re-enabled old envisalink_new yaml config, retsarted, everything back to normal. 

Next steps:

1. Remove integration via services
2. Leave old yaml config enabled
3. Update to 0.4.1 and restart
4. HA hangs again

Initial log entries look fine:

```
2023-01-31 13:22:36.624 INFO (MainThread) [homeassistant.setup] Setting up envisalink_new
2023-01-31 13:22:36.624 INFO (MainThread) [homeassistant.setup] Setup of domain envisalink_new took 0.0 seconds
```

This time left it for two minutes and then it returned with:

```
2023-01-31 13:23:30.051 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: envisalink_new
2023-01-31 13:23:30.345 INFO (MainThread) [hass_nabucasa.google_report_state] Connected
2023-01-31 13:24:30.107 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: envisalink_new
2023-01-31 13:24:46.967 ERROR (MainThread) [custom_components.envisalink_new.pyenvisalink.alarm_panel] Unable to validate connection: Cannot connect to host 192.168.25.15:8080 ssl:default [Connect call failed ('192.168.25.15', 8080)]
2023-01-31 13:24:47.002 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 138.40s
```

It looks like it is trying to connect on 8080 instead of the correct port?

HA then gives up and completes loading but reports that a "New Device" has been found - which is an empty envisalink integration. I go through the wizard again, checking that 4025 is set as the port to use and send it off to do it's thing....but it just spins and spins and spins and goes nowhere. Eventually it comes back with "! Cannot Connect". Checking the logs shows it again hammering port 8080:

```
2023-01-31 13:34:44.982 ERROR (MainThread) [custom_components.envisalink_new.pyenvisalink.alarm_panel] Unable to validate connection: Cannot connect to host 192.168.25.15:8080 ssl:default [Connect call failed ('192.168.25.15', 8080)]
```

Now to be fair the envisalink is firewalled off....should it be trying to hit 8080? If so I will add a rule....

**Comment by ufodone** [comment]
It uses port 8080 to hit the web interface on the EVL to scrape the MAC address, firmware version and hardware version and panel type.  It was previously using port 80 but I changed it to 8080 at some point.  So yes, if you can open that port on your firewall then that will likely fix your issue.

I'd planned to make this second port configurable but hadn't gotten around to it yet.  Your case is probably also good reason to do that and change the default  back to port 80.

I'll separately have a look at making this type of startup failure more obvious.

**Comment by ChirpyTurnip** [comment]
OK. Firewall updated to add 8080. Upgraded, restarted, entities doubled up, everything greyed  out and messy with dashboards broken again. Deleted integration via services, restarted, default config reloaded from yaml and.......we're all good again!

**Comment by ufodone** [comment]
All good in that you're up and running with 0.4.1?  Or all good in that you reverted back?

**Comment by ChirpyTurnip** [comment]
All good on v0.4.1 as intended. I wouldn't worry too much on the 80 vs 8080 but it was good to know so make a note if nothing else....I had that problem with other network traffic messing up the EVL so it's firewalled off - for most people it may make little difference...though there are are bound to be others with different networks too I guess....either way, rule change is easy if you know it is required. :-)

**Comment by ufodone** [comment]
I've added a timeout to the http calls now so that if a firewall is in place, it will fail much more quickly and log the error.
