### ISSUE TITLE
Zone Fault status not updating

### ISSUE THREAD

**Issue by tivo65** [ufodone/envisalink_new#122]
The zone fault status always shows "off" even when tripped to activate the alarm.  ie: set the alarm, open a door, zone 3, zone 3 fault status still shows "off".  I expected it to change to On since it was the zone tripping the alarm.  Running 0.9.1, DSC, evl_4,  latest HA versions - is there a way to know which zone tripped the alarm? BTW, just upgraded to this "_new" and it is fantastic.  thanks for all the work on the new version.

**Comment by ufodone** [comment]
Are you referring to the zone's binary sensor state not changing?  Or the "`fault` attribute on the zone's binary sensor?  If the latter, that attribute will only be set if a specific update is received from the EVL indicating a fault - and a "fault" in this case I believe refers to an actual problem with the zone as opposed to it being tripped while armed or opened while disarmed.  The `open` attribute will be set to true when a zone is tripped while the alarm is not armed.  Likewise, the `alarm` attribute should be set to true when the zone is tripped while the alarm is armed.

If you are referring to the actual binary sensor state not changing, then I'll probably need to see some debug logs to see what's going on.

**Comment by tivo65** [comment]
the zone binary sensor (that indicates if the door is open or shut) works as expected.  I was expecting the Fault attribute to change if that zone was the cause of an alarm trip.    so my confusion -   sounds like the way to know what zone tripped or setoff the alarm is to look at the zone binary sensor state for open when the alarm trips.  the only gotcha on this if a zone is bypassed (because a window was open etc), it would also show open when the alarm tripped.  when the alarm goes off it is not always easy to know what zone tripped it.  the DSC panel knows because it displays the zone at fault - let me know if you can see another way to accomplish this.

**Comment by ufodone** [comment]
I think you could use the `alarm` attribute instead of the sensor state to determine if the zone is in alarm/faulted.  That should solve your first gotcha.  For the second one, it might be better to take the approach discussed [here](https://github.com/ufodone/envisalink_new/discussions/57) which relies on the `last_tripped_time` attribute.

**Comment by tivo65** [comment]
thanks, that link is very helpful to the other post outlining the last_tripped_time - that is the same problem i am trying to address.    since I can see on my dsc control panel the zone that caused the alarm to go off it seems like that would be data the evl board would have available.  thanks for your help
