### ISSUE TITLE
Panic switches for Police, Ambulance, and Fire.

### ISSUE THREAD

**Issue by akagarwal** [ufodone/envisalink_new#126]
### Discussed in https://github.com/ufodone/envisalink_new/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **akagarwal** July 14, 2024</sup>
Hi,
I am new to Home Assistant and recently migrated from HomeBridge + HomeKit. I got this integration to work perfectly except I don't see the three panic switches for Police, Ambulance, and Fire that were available in HomeBridge plugin. I am trying to setup an automation in HA to activate Fire panic automatically if no one is home and my smoke detectors activate. Can someone please help on how to setup these panic buttons. Thank you!</div>

**Comment by ufodone** [comment]
This integration doesn't currently expose explicit switches for Police, Ambulance and Fire.  However, if it's just triggering Fire that you're after, I suspect you might be able to do the following:

In `Settings -> Devices & Services -> envisalink_new -> Configure -> Advanced`, set the `Panic Type` to `Fire`.

Once that is done, you should be able to use the `alarm_control_panel.alarm_trigger` service call in your automation.  I believe this should have the same effect as pressing the `Fire` button on your physical keypad.

The service call would look something like:

```
service: alarm_control_panel.alarm_trigger
target:
  entity_id: alarm_control_panel.home_alarm
```

**Comment by akagarwal** [comment]
Thank you. I saw the settings but figured those were for normal alarm triggers when a zone is opened while armed and it should be set to police for that so I would prefer not to change that. I was hoping for a separate fire trigger that I can activate for smoke but since that capability is not exposed, I will just use a notification to myself and be the human trigger for fire alarm for now. BTW: is this a technical limitation of this integration or just needs additional feature development?

**Comment by ufodone** [comment]
> is this a technical limitation of this integration or just needs additional feature development?

I'm not the original author of the `envisalink` integration so can't speak to the original intent but my guess is that the HA alarm_control_panel entity only supported a single trigger and so this configuration setup was designed to map one of the three possible actions onto it so people could use the default functionality of the alarm_control_panel.

The EVL/DSC device itself does support triggering each of the three options.  It should be possible to add new service calls that could be used to trigger it.

**Comment by ufodone** [comment]
FYI I have added some push button entities in v0.9.3 which you can use to trigger each of the three panic buttons.
