### ISSUE TITLE
Bell Circuit Trouble Status

### ISSUE THREAD

**Issue by BobRobertBob** [ufodone/envisalink_new#137]
I would like to request the addition of Bell Circuit Trouble status similar to AC Power and Battery. The Bell circuit is monitored by the DSC panel (for an open circuit) and like the battery and AC power, it is useful to monitor it's status.

**Comment by ufodone** [comment]
Added in v0.9.3.

**Comment by BobRobertBob** [comment]
Just tested (by removing siren connection at panel).  No issues.

Thank you for adding this feature.
