### ISSUE TITLE
"Armed/Disarmed By" Attribute not Populating

### ISSUE THREAD

**Issue by dwmead86** [ufodone/envisalink_new#143]
The "last armed by user" and "last disarmed by user " attributes on the keypad display is not populating with a user number anymore.   I have tried rebooting my envisalink module, ive deleted and reconfigured the integration, with no luck.

**Comment by ufodone** [comment]
Is this for a Honeywell or DSC system?

**Comment by ufodone** [comment]
@dwmead86 I haven't heard back from you for a couple months so I'm closing this.
