### ISSUE TITLE
"Failed setup, will retry"  Was working for a day then getting this error HAOS Envisalink4  (see pics)

### ISSUE THREAD

**Issue by nutshellml** [ufodone/envisalink_new#144]
Hi, Running HAOS (latest Core), everything updated, have Vista20p with Envisalink 4.  Setup everything labeled zones now i'm getting an error.  Was working for less than a day then overnight notice this error and can't clear it with restarts

![image](https://github.com/user-attachments/assets/090fb96d-3423-46ff-93d1-72f77c1a7376)

![image](https://github.com/user-attachments/assets/580e1a14-f1ba-4ea2-b92e-9867f45f4d21)

![image](https://github.com/user-attachments/assets/09386c20-3949-40a3-b974-72a1a5b3873e)

**Comment by ufodone** [comment]
Are there any errors or warnings in your HA logs related to the integration?  I would expect there to be something in there given that setup error.  If not, could you enable debug logging for `envisalink_new`?

**Comment by nutshellml** [comment]
Okay I enabled it.  In the interim it seemed to pop back and now working well.

**Comment by nutshellml** [comment]
Okay so I happened again, just came home today and checked "Failed Setup, will retry".  How do I get the logs to send?

![image](https://github.com/user-attachments/assets/bb53716c-2b7c-4f4e-aa66-c7f18e1eb2af)
![image](https://github.com/user-attachments/assets/ca19fe27-f53a-497f-b690-709277dceab7)

**Comment by nutshellml** [comment]
Here's the log
[home-assistant_envisalink_new_2024-10-07T20-06-08.029Z.log](https://github.com/user-attachments/files/17283932/home-assistant_envisalink_new_2024-10-07T20-06-08.029Z.log)

**Comment by ufodone** [comment]
That looks like something else is already connected to the EVL device.  It (unfortatunely) only allows a single connection at a time on port 4025 and will close any additional connections - as is happening in your logs.

If you were using the stock `envisalink` integration before, did you comment out or remove that configuration from your configuration.yaml?  Or do you have another instance of HA (or some other system) also running which might be configured to connect to the EVL?

**Comment by nutshellml** [comment]
That was it - my old vera was still connecting to it.  I removed the vera evl plugins and now seems to be working perfectly.  Thanks brother! stay safe!
