### ISSUE TITLE
2024.11.0 Depreciation warnings

### ISSUE THREAD

**Issue by Nick425321** [ufodone/envisalink_new#151]
2024.11.0 has introduced the following deprecation warnings:

Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 05:42:57 (6 occurrences)
Last logged: 05:42:57

STATE_ALARM_ARMED_HOME was used from envisalink_new, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'envisalink_new' custom integration
STATE_ALARM_ARMED_NIGHT was used from envisalink_new, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_NIGHT instead, please report it to the author of the 'envisalink_new' custom integration
STATE_ALARM_DISARMED was used from envisalink_new, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'envisalink_new' custom integration
STATE_ALARM_PENDING was used from envisalink_new, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.PENDING instead, please report it to the author of the 'envisalink_new' custom integration
STATE_ALARM_TRIGGERED was used from envisalink_new, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'envisalink_new' custom integration

Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:210
integration: Alarm control panel (documentation, issues)
First occurred: 05:42:58 (1 occurrences)
Last logged: 05:42:58

Entity None (<class 'custom_components.envisalink_new.alarm_control_panel.EnvisalinkAlarm'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

**Comment by ChipSkylark37** [comment]
Echoing the above - Upgraded HA recently and have been reviewing log files and came across the same 'warning'.

**Comment by ufodone** [comment]
Thanks for reporting.  These should be fixed in v0.9.3.
