### ISSUE TITLE
EVL-4 in Standalone Mode (UNO) Fails To Detect Panel Type

### ISSUE THREAD

**Issue by clearwave1** [ufodone/envisalink_new#154]
I have an EVL-4 that has the Standalone (UNO) firmware installed.

When trying to setup the integration, I get the following error:

Failed setup, will retry: Unrecognized/undetermined panel type at 192.168.x.x

This happens after the setup of the integration in the Devices & Services screen is successful.

**Comment by ufodone** [comment]
Can you check your logs for additional warnings/errors?  There should be something there which provides additional information what the integration is getting back from the EVL device.

I'm not familiar with your setup.  Is that the equivalent of the Uno Hybrid system but running on an EVL4 board?

**Comment by clearwave1** [comment]
Thanks for the quick response.

Here is what I get:
This error originated from a custom integration.

Logger: custom_components.envisalink_new.pyenvisalink.alarm_panel
Source: custom_components/envisalink_new/pyenvisalink/alarm_panel.py:271
integration: Envisalink_new (documentation, issues)
First occurred: 10:01:32 AM (2 occurrences)
Last logged: 10:01:37 AM

Unexpected panel type: 'UNO STANDALONE'

This is equivalent to the UNO Hybrid on an EVL-4 board. You can see the details on Eyezon's website here:
https://www.eyezon.com/uno.php 

There is also a link to a setup manual on that page but essentially it downloads the firmware of the UNO Hybrid to the EVL-4.

**Comment by ufodone** [comment]
Thanks for the info.  That's an additional UNO variant that I was not aware of.  I'll need to update the code to detect `UNO STANDALONE` as an Uno device.

**Comment by clearwave1** [comment]
Let me know if you would like me to test once you have a pre release version.

**Comment by ufodone** [comment]
I've posted a v0.9.5 release which should fix the detection issue.  I'm assume this UNO STANDALONE device is equivalent to the "UNO IP Hybrid" product EyezOn sells and so the integration will treat it as such.  Uno support is somewhat limited at the moment due to limitations in the firmware (but updates are apparently coming).

**Comment by clearwave1** [comment]
Thanks. I've tested this and it now detects the device properly and sets up the integration.
