### ISSUE TITLE
Honeywell Vista Arm Stay Instant

### ISSUE THREAD

**Issue by Blueion76** [ufodone/envisalink_new#156]
Hi, I have my Honeywell Vista 20P panel set to Instant mode for Arm Night. After updating from 0.9.2 to the latest version I noticed the alarm control panel entity is being reported as Armed Home instead of Armed Night like it used to be. I think this is partly related to issue #146.

See attached screenshots. 

![image](https://github.com/user-attachments/assets/a1f33527-e408-4cf2-8d64-a742c6136b71)
![image](https://github.com/user-attachments/assets/4ec8ae2f-05be-4253-95b0-282f57ad659c)

**Comment by ufodone** [comment]
I've posted a new release (v0.9.6) which should fix this issue.

**Comment by Blueion76** [comment]
> I've posted a new release (v0.9.6) which should fix this issue.

That fixed it. Thanks!
