### ISSUE TITLE
Integration isn't picking up the yaml as envisalink_new

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#16]
Integration isn't picking up the yaml as envisalink_new. Renaming back to envisalink allows the integration to read the config on startup.  Here's the integration shown on the Devices&Services screen:

![envisalink](https://user-images.githubusercontent.com/47036329/217889850-53ac4d8a-dc2c-4397-bd0c-92e86c7e1f01.jpg)

Needed to comment out the envisalink config and restart to allow me to add the envisalink_new integration. Once added, the yaml config needs to be in place for HA to load envisalink_new at startup. I haven't found the config entity.

I haven't been able to get envisalink_new to create the devices and services provided by the old envisalink component.

_Originally posted by @garyak in https://github.com/ufodone/envisalink_new/issues/1#issuecomment-1424553863_

**Comment by ufodone** [comment]
How did you install this manually?  In `config/custom_components/` or directly into the HA installation?

Are there any errors in your log file?  If not, can you try turning on debug logging:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: info
```

(The logging setup will likely only work if you installed it in `config/custom_components/`)

Do you have a firewall or anything that might be blocking access to the EVL?  The new integrating uses both port 4025 (for the main connection) but also port 8080 to interrogate the device to obtain the MAC address and some other info.

The intent is certainly that you only need to rename `envisalink:` to `envisalink_new:` in your configuration.yaml and restart HA.

**Comment by garyak** [comment]
I think I've got it working now. I Deleted the integration shown above, renamed the header back to envisalink_new, and restarted again. This is the result:

![envisalink](https://user-images.githubusercontent.com/47036329/217903748-771fd9ec-12ef-4f43-b796-bdc3162126fd.jpg)

it seems, I had two, overlapping integrations installed. Not certain how, but deleting the one shown on the Devices&Services page exposed this one.

I captured some data before I deleted the integration with the header envisalink_new.
[alarmlogging.txt](https://github.com/ufodone/envisalink_new/files/10700402/alarmlogging.txt)

**Comment by garyak** [comment]
I installed into config/custom_components, left original envisalink config header, and restarted HA. I thought the new component would read the existing envisalink config and adopt the config for itself. No go. Next, I commented out the envisalink header and restarted, but still no devices/service. I then rechecked the Add Integrations to find that Envisalink_new had appeared in the list, so I installed the integration from Devices&Services page. Following that, the configure dialog was requesting the Host IP, credentials, and other items. It was clear it hadn't discovered the existing configuration.

**Comment by ufodone** [comment]
Right, it can't automatically pull from `envisalink:` in your config because you can't have two integrations with the same domain (name) and it's that domain that determines what to look for in configuration.yaml.  I had to create a new name to avoid the conflict which means you need to rename your configuration entry (for now).

Because the changes are quite substantial, I wanted a way to allow volunteers to help me test in a safe way that allowed an easy way to switch back if there were problems.  Once I'm comfortable that things are solid, I'll be submitting the changes back to HA to replace the existing `envisalink` integration - at which point the `_new` naming will go away.

**Comment by garyak** [comment]
I'll run with your new code and report any irregularities. Sorry for the distraction. I misinterpreted the simple instructions given. It's been quite awhile since this component has been looked at. Thanks for taking this update on. It's one of the most valuable components at my house.

**Comment by ufodone** [comment]
Thanks for testing!

**Comment by rct** [comment]
FWIW - I see this issue is closed, but I'm not drawing a conclusion from reading this.

Is the answer that manual YAML configuration (at least of the connection details like host, user, password) won't work at this point because of the `envisalink:` vs `envisalink_new:` integration/config block naming?

**Comment by ufodone** [comment]
Manual YAML configure does work and will continue to work (assuming I don't break anything accidentally).  The issue is that you cannot have entries for both `envisalink` and `envisalink_new` in your configuration.yaml because they will both be imported automatically and both try to connect to the same device.

So if you are using `envisalink_new`, all you should have to do to switch to it is rename `envisalink:` to `envisalink_new:` and restart HA.  

Once I feel it's ready, my plan is to submit this integration as a PR into Home Assistant to *replace* the existing `envisalink` integration.  At that point, I will switch it to pick up `envisalink:` from configuration.yaml.  I just can't do that right now because the integration needs to have a unique name so it doesn't create a conflict.

**Comment by rct** [comment]
> So if you are using `envisalink_new`, all you should have to do to switch to it is rename `envisalink:` to `envisalink_new:` and restart HA.

Ok, That's what I thought I did, but apparently I'm an idiot and left the old `envisalink:` key around.   Sorry about that. 

Now that I fixed that and restarted, but there is still a problem that the integration isn't configured.

I just see now that you created #18.  I'll reply there.
