### ISSUE TITLE
Help with zones only showing closed

### ISSUE THREAD

**Issue by bwoods113** [ufodone/envisalink_new#160]
### Discussed in https://github.com/ufodone/envisalink_new/discussions/159

<div type='discussions-op-text'>

<sup>Originally posted by **bwoods113** December 16, 2024</sup>
I went through the setup and everything went as expected. I added my zones from the configuration button and I see all 16 zones. The only problem is that they never change from being "closed". I know zone 4 is our interior garage door, I open in and see that reflected when I am logged into the eyezon website but it is not reflecting in HA. Any help is greatly appreciated. Thank you for looking.
![alarm 4](https://github.com/user-attachments/assets/5b35500d-4256-49b2-a3f8-d26d872d4190)
![alarm 3](https://github.com/user-attachments/assets/ded02f9c-f527-4306-a2f2-edd32e460a89)
![alarm 2](https://github.com/user-attachments/assets/8f7bef49-7e7b-45bd-91a0-d13b03a7281d)
![alarm 1](https://github.com/user-attachments/assets/b2564f1e-dd2a-4b97-a0c6-04112697392b)</div>

**Comment by ufodone** [comment]
Is it just the zone status that isn't updating?  E.g., are you able to arm/disarm the alarm via Home Assistant? 

Are there any errors or warnings in the logs?  If not, could you enable debug logging for `envisalink_new` and then open and close some zones and post the logs here?  That will hopefully give some indication of what's going on.

**Comment by bwoods113** [comment]
I apologize, I was able to work with eyezon support and there was a setting in my alarm system that was preventing the communication. All is working perfect now. Appreciate your response and all your hard work.
