### ISSUE TITLE
Notes on using AlarmServer with Envisalink_new

### ISSUE THREAD

**Issue by rct** [ufodone/envisalink_new#19]
Collecting a few notes for those who might be using AlarmServer (DSC/Juggie) as an Envisalink proxy to enable multiple connections.  My notes are for DSC, I don't have a Honeywell system to test yet.

**Current status:**  Seems to be working, but may need some steps to get it to work.

1. New discovery process requires HTTP fetching the network page (/3) from the Envisalink to determine the Envisalink's MAC address for unique ID and the firmware version.  You will need to arrange a proxy, or cached copy of the HTML page on the same hostname/IP as your AlarmServer.
2. Some versions of AlarmServer don't acknowledge the login command `005` with a `5000052A` response. The updated pyenvisalink needs to see this response.  See #18.
3. The updated Envisalink integration logs unexpected responses from the Envisalink as an error.  Since AlarmServer does an Envisalink ping `000` periodically, there will be periodic errors logged.  `2023-02-12 12:56:00.300 ERROR (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client] Command acknowledgement received for '000' when no command was issued.`

**Comment by Gibby** [comment]
> Collecting a few notes for those who might be using AlarmServer (DSC/Juggie) as an Envisalink proxy to enable multiple connections. My notes are for DSC, I don't have a Honeywell system to test yet.
> 
> **Current status:** Seems to be working, but may need some steps to get it to work.
> 
> 1. New discovery process requires HTTP fetching the network page (/3) from the Envisalink to determine the Envisalink's MAC address for unique ID and the firmware version.  You will need to arrange a proxy, or cached copy of the HTML page on the same hostname/IP as your AlarmServer.
> 2. Some versions of AlarmServer don't acknowledge the login command `005` with a `5000052A` response. The updated pyenvisalink needs to see this response.  See [Manual YAML configuration not working #18](https://github.com/ufodone/envisalink_new/issues/18).
> 3. The updated Envisalink integration logs unexpected responses from the Envisalink as an error.  Since AlarmServer does an Envisalink ping `000` periodically, there will be periodic errors logged.  `2023-02-12 12:56:00.300 ERROR (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client] Command acknowledgement received for '000' when no command was issued.`

Any instructions for doing those 3 things?

**Comment by ufodone** [comment]
Release [v0.8.0](https://github.com/ufodone/envisalink_new/releases/tag/v0.8.0) has support for specifying a different address for the discovery process which can be used to address item 1.  

The other two issues are caused my AlarmServer not conforming to the TPI protocol and something that would need to be fixed in AlarmServer.
