### ISSUE TITLE
Time push to DSC system

### ISSUE THREAD

**Issue by schmuy** [ufodone/envisalink_new#23]
I don't know if this is related to the integration or something else, it could be a number of factors.  I don't even know if the integration pushes the current time back to the system or if that's the EVL card and a separate thing..

I noticed this morning the time displayed on my physical DSC keypads was -3h off.  I just migrated my HA instance to a new machine last night so maybe something happened with that?  I checked HA time zone and everything was correct.  I restarted HA and checked back a while later and it was correct again.

I was on v0.4.1 at the time and have since upgraded to 5.2.  This could be a non-issue, but I thought I'd mention it.

**Comment by ufodone** [comment]
The integration will push the time to the EVL on initial connection.  My guess would be that when you migrated to a new HA instance, you maybe set the timezone in HA after it had initially started up so when the envisalink integration initially started the timezone may have been wrong so it sent the wrong time to the EVL. When you restarted HA, it would have logged back into the EVL and re-set the time based on the correct timezone.
