### ISSUE TITLE
Works perfectly on 2 panels.

### ISSUE THREAD

**Issue by bluezclouds** [ufodone/envisalink_new#30]
Device:  Raspberry Pi 3+, 1g memory, 64g MicroSD 
OS:  Raspbian GNU/Linux 11 (bullseye)
Environment:   Home Assistant 2023.3.6, Supervisor 2023.03.2, Frontend 20230309.1 (latest versions.)  
(Full install on Raspberry Pi OS)
Installed evisalink_new via HACS
Managed Alarms:  2 separate Envisalink 4 panels, one local, one accessible via an IP route through a VPN tunnel.  

Mistakenly left an existing config in an Envisalink portion of the configuration.yaml.  When I tried to add it a 2nd time the integration showed an error with the device (as it should have.) 

Went ahead and added the 2nd Envisalink 4 and the new device worked perfectly.  

Realized my error and renamed the evisalink yaml heading to evisalink_new and my 1st panel came up immediately after restart, right alongside the panel added with the evisalink_new integration.

Deleted the envisalink_new section of the file with the intention of adding the 1st panel through the integration and to my surprise the 1st panel continued to work perfectly upon restart.  

No problems after 24 hours.  

Thanks much for a great integration!

**Comment by ufodone** [comment]
Thanks for confirming multiple panels!
