### ISSUE TITLE
Cannot disarm with HA when alarmed trigger via service

### ISSUE THREAD

**Issue by Damien2s** [ufodone/envisalink_new#32]
Hello,

First thanks for this great work.
Secondly I ran the tests as recommended (with configuration.yaml, I did not try with a new install). All worked as expected.

Today, I've decided to make a couple of automation (standard and red-node) which trigger the alarm via a service Call.
Both work i.e. trigger the alarm. I've tried with both panic type (Police and Fire). They are triggered as expected.

My only problem was when I tried to stop the alarm I realized that HA panel was in "Disarmed" mode. Hence I wasn't able to enter the code and stop the alarm from HA.
I've run several tests and I noticed that each time I send the service call, for half a second the HA alarm panel shows that the alarm is triggered but immediately comes back to "Disarmed" mode. 

I've got a DSC 1864 with an Envisalink 4 FW 01.04.176

**Comment by ufodone** [comment]
I assume this works correctly when you manually trigger these alarms via the UI? 

Could you provide some debug logging of this happening?  You can enabling with something like the following in your configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```

**Comment by Damien2s** [comment]
Actually the same issue happens when triggered manually from the UI.

Here below is the log file. The alarm was triggered at 20:39:04

[home-assistant_envisalink_new_2023-04-11T01-39-53.738Z.log](https://github.com/ufodone/envisalink_new/files/11195340/home-assistant_envisalink_new_2023-04-11T01-39-53.738Z.log)

**Comment by ufodone** [comment]
Thanks for the logs.  It looks like what's happening is that the EVL is sending an update that the "Fire" key has been pressed followed by an update that the alarm has been triggered followed by an update indicating that the "Fire" key has been restored - all within the same second.  

The code appears to treat that last update ("key restored") as an indication to clear the alarm.  It clears the "fire" attribute and clears the fact that the panel is in alarm.  I didn't write this code and don't use the this functionality myself so can't say why it currently works this way.  From the logs, my guess would be that it should not clear the alarm when the "key restored" update is received.  That would fix your issue but it would also clear the "fire" attribute even while the panel is still in alarm - which is maybe okay?

**Comment by ufodone** [comment]
@Damien2s I'm trying to figure out what to do about this.  There seems to be Fire, Aux, and Panic keys as well as a Duress code and a "2-Wire Smoke/Aux Alarm" as ways that can trigger some form of alarm.  Do you know whether all of these will activate the alarm such that they require it to be disarmed like is the case with the Fire case you have been testing?

**Comment by ufodone** [comment]
@Damien2s Sorry for the delay.  I've posted a [beta release](https://github.com/ufodone/envisalink_new/releases/tag/v0.6.7-beta.1) which I hope will fix your issue.  I don't have an easy way to test it on my physical alarm but using the logs you provided I was able to simulate the behaviour.  You will need to enable `Show beta versions` in the `Redownload` menu for the integration in HACS in order for it to show up as an installable version.

Could you please give it a try and let me know if it fixes the issues?  If there are still issues, can you capture debug log of the failures so I can have a look?  Thanks!

**Comment by Damien2s** [comment]
@ufodone thanks for the support. so I've tested the beta and it's almost fixed: now the HA panel turns into "triggered" mode when I use the panic keys. I can enter the code and disarm the alarm (it shows disarmed on the DSC UI) but the HA panel stay stuck on "triggered" mode (flashing red). It doesn't switch to disarmed mode.
When stuck on triggered mode:
 -  if I re-trigger the alarm, I can still disarmed it via the stuck HA panel, but it remain stuck. 
 -  if I arm then disarm both from the DSC UI, the HA panel get back to normal in "Disarmed" mode and I can operated the HA panel properly.

The log follow the sequence described above:
[home-assistant_envisalink_new_2023-06-09T16-20-24.111Z.log](https://github.com/ufodone/envisalink_new/files/11708358/home-assistant_envisalink_new_2023-06-09T16-20-24.111Z.log)

**Comment by ufodone** [comment]
Glad things are looking better and thanks for the logs.  I've pushed a new [beta release](https://github.com/ufodone/envisalink_new/releases/tag/v0.6.7-beta.2) which I believe should fix the issue.

It seems that when you disarm the alarm when it has been activated by the Fire/Panic keys, it sends a different update to indicate the alarm has been disarmed than is usually the case for a disarm action.

**Comment by progamer562** [comment]
omg yes fixed my issue
