### ISSUE TITLE
Reconnection attempts

### ISSUE THREAD

**Issue by larry-glz** [ufodone/envisalink_new#33]
So far the integration works great.  But i do see a lot of reconnection attempts in the logs.

```
This error originated from a custom integration.

Logger: custom_components.envisalink_new.pyenvisalink.envisalink_base_client
Source: custom_components/envisalink_new/pyenvisalink/envisalink_base_client.py:144
Integration: Envisalink_new
First occurred: April 27, 2023 at 5:11:08 PM (142 occurrences)
Last logged: 2:16:31 PM

Reconnection attempt in 30s
```

followed by

```
This error originated from a custom integration.

Logger: custom_components.envisalink_new.pyenvisalink.envisalink_base_client
Source: custom_components/envisalink_new/pyenvisalink/envisalink_base_client.py:500
Integration: Envisalink_new
First occurred: April 27, 2023 at 5:11:08 PM (142 occurrences)
Last logged: 2:16:31 PM

Command '00' failed due to timeout waiting for response from EVL
```

The alarm becomes available soon after.  Any ideas what could be causing this?  thanks!

**Comment by ufodone** [comment]
What version of the Envisalink firmware are you running?  I've seen similar issues with older firmware versions.

**Comment by larry-glz** [comment]
01.04.184A 
What I haven’t been able to pin down is if an HA reboot heals this or arming/disarming the system does. I haven’t been able to reproduce it. But somehow the issue goes away for days until it comes back mysteriously. This may be TMI, but the alarm is scheduled to arm/disarm on a daily basis. And so far hasn’t failed to do either.

**Comment by ufodone** [comment]
That firmware should be fine.

However, my experience is that the EVLs can be a bit finicky and I've seen lot of people (myself included) hit by similar issues.  It typically ends up getting tracked down to the EVL itself becoming non-responsive for periods of time.  What triggers the unresponsiveness has varied but usually involves the EVL receiving some form of traffic at an inopportune time.  Sometimes that traffic has come from this HA integration and other times it's come from elsewhere (I believe someone's Plex server was querying devices on the network which was causing it to trigger).  Needless to say it's frustrating to track down.

A few thoughts:
1. If it comes and goes, is there anything else that changes on your network in similar intervals that could be interfering?
2. If you could enable debug logging for the integration and capture this happening, I'd be happy to take a look and see if there's any hints there.  Debug logging will introduce a lot of logs though so be aware of that before you turn it on.
3. If it's always the '00' command failing, you could change your `keepalive_interval` to something much larger to see if that reduces the frequency.  Not a fix but maybe some relief at least.

To enable debug logging, add something like below to your configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```

**Comment by larry-glz** [comment]
i'll try this and try to catch the log entries when it's in this reconnection loop.  thanks

**Comment by larry-glz** [comment]
see attached for some of the log trace.  only 2 instances of this yesterday.  i capture a full day's worth of log if needed.
[log.txt](https://github.com/ufodone/envisalink_new/files/11415288/log.txt)

**Comment by ufodone** [comment]
The log file contains many duplicated lines but only for the underlying `pyenvisalink` logs which is odd.  Are you seeing these duplicated lines in your raw log files on your HA host?  

If this isn't just a logging issue, it's pretty odd as it looks like there are three connections to the EVL when there should only be one (which is also enforced by the EVL itself).  Do you use anything in-between your HA and the EVL such as AlarmServer?

**Comment by larry-glz** [comment]
> The log file contains many duplicated lines but only for the underlying `pyenvisalink` logs which is odd. Are you seeing these duplicated lines in your raw log files on your HA host?
> 
no.  only seem to be the pyenvisalink entries that are triplicated
> If this isn't just a logging issue, it's pretty odd as it looks like there are three connections to the EVL when there should only be one (which is also enforced by the EVL itself). Do you use anything in-between your HA and the EVL such as AlarmServer?
>
... and no.  i'll try removing the integration altogether, restarting, restarting again to try to clear up stuff, re-installing the integration, restarting, setting up the integration, restarting... and monitor the logs to see if that clears up the "gunk"

**Comment by ufodone** [comment]
A complete log from when you start HA to when the issue first occurs could be helpful to track this down.  If that logging is indicative of an issue with the integration, logging from startup may provide some clues as to what's going on.

**Comment by ufodone** [comment]
Unfortunately, I don't see anything unusual in that latest log that could point to a problem.

All the other keep-alive commands (^00) sent get a response back almost immediately but periodically something seemingly delays the response long enough for the command to timeout.  That could be the EVL itself becoming slow/unresponsive or possibly a network delay (is your HA on WiFi?) or your HA host getting sluggish.  

If you're able to do a network capture between the HA host and your EVL and capture the period of time when the timeout occurs, that could help narrow down the root cause.  But I know that's not something many people are setup to do.

**Comment by larry-glz** [comment]
both the EVL and HA (raspberry) are wired.  i think i'll leave it alone for now, or at least until i find the time to setup the packet capture.  i see very low incidence of this now (maybe the reinstall helped) and the EVL-related entities seem to continue to function ok.
