### ISSUE TITLE
Bypass switches not showing up

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#35]
Thank you for your efforts...
1. Running v06.6
2. Dsc panel- I believe it's evl-3
3. I'm seeing the status of all of my 15 zones.
4. Integration is creating 17 entities
5. I'm not seeing the option under Advanced Config to create the Bypass switches nor am I seeing in devices/entities.

I had created a lot scripts that need to be modified to mimic the control panel using the Envisalink integration. Once I can sort the Bypass issue, which is my primary requirement, then I will update the automation/scripts/etc....

**Device info**
Envisalink 4: DSC
by eyezon
Firmware: 01.04.188
Hardware: 4

_Originally posted by @najikarim in https://github.com/ufodone/envisalink_new/issues/1#issuecomment-1566249031_

**Comment by ufodone** [comment]
@najikarim I assume that `Device Info` you provided is directly from the UI's device page?  

Did you create your setup strict from the HA UI or do you have an `envisalink_new` section in your configuration.yaml?  If the latter, could you post that configuration here (minus any password/code you have have in there).

If possible, it would also be helpful to see the config entry for the device.  That will be in the HA `config/` directory in a file called `.storage/core.config_entries` and the entry would look something like:

```
      {
        "entry_id": "5642069b18e3c6e6f4459de93905322d",
        "version": 1,
        "domain": "envisalink_new",
        "title": "Alarm",
        "data": {
          "host": "192.168.1.2",
          "user_name": "user",
          "password": "***",
          "partition_set": "1",
          "zone_set": "1-8",
          "code": "***",
          "port": 4025,
          "discovery_port": 80,
          "evl_version": 4,
          "panel_type": "DSC"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "01:02:03:04:05:06",
        "disabled_by": null
      }
```

Again, make sure to remove any password/code that may be present.

**Comment by najikarim** [comment]
1.   **I assume that Device Info you provided is directly from the UI's device page**?
 Yes, that came from the UI.

2.  **Did you create your setup strict from the HA UI or do you have an envisalink_new section in your configuration.yaml?**
  I started with configuration.yaml. Since that did not work (no bypass switches), I commented all the entries in the configuration.yaml relating to the Envisalink.

I then used the Envisalink_new UI to configure all the parameters. I then rebooted the system (Homeassistant is running on a Pi 4).
I erased UserName, Password, Alarm Code from the attached..

![Screenshot (8)](https://github.com/ufodone/envisalink_new/assets/53799358/4c99f480-15c4-4744-acae-75ef696342ab)
![Screenshot (9)](https://github.com/ufodone/envisalink_new/assets/53799358/5fd94d03-3a7a-4eb9-b340-e0c81a5f0bba)

3. **If possible, it would also be helpful to see the config entry for the device. That will be in the HA config/ directory in a file called .storage/core.config_entries**

I do not have such a file in my config directory, may be that is the problem:

![Screenshot (10)](https://github.com/ufodone/envisalink_new/assets/53799358/58ae108d-e51f-4f0d-8eaf-694fb3fcdbf0)

**Comment by ufodone** [comment]
>I do not have such a file in my config directory, may be that is the problem:

It looks like the `.storage` directory is filtered out by default but you can go into the File Editor add-on's configuration and remove it from the `Ignore Pattern` setting.

>I started with configuration.yaml. Since that did not work (no bypass switches)

There isn't currently an option to enable the bypass switches in the `configuration.yaml` but you can still turn it on via the UI's advanced configuration for the integration even with the core settings in `configuration.yaml`.

However, I suspect config state got messed up as part of the procedure you followed and I'd like to track down what happened.  I haven't been able to reproduce this myself so if you still have the `configuration.yaml` settings that you used, could you attach them and also that config entry from `core.config_entries` file?  Also check to see if there are multiple `envisalink_new` entries in that file.

Thanks!

**Comment by najikarim** [comment]
As I mentioned all entries have been commented and there are no other Envisalink entries in the configuration.yaml

I had added the the create_bypass_switches after the first attempt but then commented it out…

#envisalink:
#envisalink_new:
#  host:  xx.xx.xx.xx
#  panel_type: DSC
#  user_name: xxxx
#  password: xxxx
#  create_bypass_switches: true
#  code: "xxxx"
#  port: 4025
#  evl_version: 4
#  keepalive_interval: 60
# zonedump_interval: 10
#  timeout: 10
#  panic_type: Police

#  zones:
#    1:

Here is the core.config_entries and that is the only entry that contains envisalink:

{
        "entry_id": "7e61e55df5bdaf195807f469e54d450b",
        "version": 1,
        "domain": "envisalink_new",
        "title": "Alarm",
        "data": {
          "host": "xx.xx.xx.xx",
          "user_name": "xxxxxx",
          "password": "xxxxxx",
          "partition_set": "1",
          "zone_set": "1-15",
          "port": 4025,
          "discovery_port": 80,
          "evl_version": 4,
          "panel_type": null,
          "code": "xxxx"
        },
        "options": {
          "panic_type": "Police",
          "keepalive_interval": 60,
          "timeout": 30
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "xx:xx:xx:xx:xx:xx",
        "disabled_by": null
      }


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ufodone** [comment]
This line is the problem:

```
"panel_type": null,
```

Unfortunately I've been unable to reproduce this issue though.  

Have you tried deleting the device from the UI and then re-adding it?  I'm curious if it ends up in the same state?  If it does, can you enable debug logging for the integration when going through the delete / re-add steps?

To enable debug logging, you'll need to add something like this to configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```

**Comment by najikarim** [comment]
Well, good news finally...

Un-installing the integration and re-installing it back fixed the problem. The new integration created 32 entities, boolean sensors and bypass switches.

Thank you for your patience and advise.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Doughboy68** [comment]
Mine works on two different systems...

Device info
Envisalink 3: DSC
by eyezon
Firmware: 01.12.205
Hardware: 3
(this one is an old one but works fine)

Device info
Envisalink 4: DSC
by eyezon
Firmware: 01.04.176
Hardware: 4



![image](https://github.com/ufodone/envisalink_new/assets/16811687/eff334c5-3e40-47a3-a002-26780647e4d8)

**Comment by Gibby** [comment]
> Mine works on two different systems...
> 
> Device info Envisalink 3: DSC by eyezon Firmware: 01.12.205 Hardware: 3 (this one is an old one but works fine)
> 
> Device info Envisalink 4: DSC by eyezon Firmware: 01.04.176 Hardware: 4
> 
> Dashboard I made... using Mushroom Template card... icons change depending on state and can press to toggle bypass on/off.
> 
> ![image](https://user-images.githubusercontent.com/16811687/246689016-eff334c5-3e40-47a3-a002-26780647e4d8.png)

Mind sharing your lovelace for the Zone status?

**Comment by Doughboy68** [comment]
For that I used mushroom template card... I create everything in a vertical stack to keep organized, then add individual stacks.. that one is a grid of 3 wide (making it a grid I can easily change if want)... then I use mushroom templates... here is example and you should be able to make work with your entities...

![image](https://github.com/ufodone/envisalink_new/assets/16811687/e37e367f-60eb-4fba-8463-77ac1331e1aa)

For the Icon:

{% if is_state('binary_sensor.home_alarm_zone_5_front_door','off') %}
{% set icon = "mdi:door-closed" %}
{% elif is_state('binary_sensor.home_alarm_zone_5_front_door','on') %}
{% set icon = "mdi:door-open" %}
{% endif %}
{{icon}}

For color:

{% if is_state('binary_sensor.home_alarm_zone_3_hallway_motion','off') %}
{% set color = "green" %}
{% elif is_state('binary_sensor.home_alarm_zone_3_hallway_motion','on') %}
{% set color = "red" %}
{% endif %}
{% if is_state('switch.home_alarm_zone_3_hallway_motion_bypass','on') %}
{% set color = "orange" %}
{% endif %}
{{color}}

Note: that the color gets overridden by the bypass state set to orange regardless if off or on.

I put the "Hallway" in Secondary information,  (not shown in screen grab) and default Tap Action is Toggle.
