### ISSUE TITLE
Invalid Authentication

### ISSUE THREAD

**Issue by zombielinux** [ufodone/envisalink_new#36]
In setting up the new integration, I'm getting "Invalid Authentication" errors. 

The username/password that matches the website doesn't function, neither does the user_name/password from the default envisalink integration (that previously works).

There doesn't appear to be anything in the logs. 

Any ideas?

**Comment by ufodone** [comment]
This integration will attempt to authenticate (and gather additional info) from the web portal on the envisalink device itself (http://<envisalink_ip>:80).  Do you have a firewall or anything blocking access to that endpoint?  Are you able to login with your username/password if you hit that page from your web browser?

You may get more info if you turn on debug logging for the integration.  You can do this by adding something similar to the following to your configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```

**Comment by zombielinux** [comment]
Solved. In the past I had already set a password. and the old yaml integration worked just fine with the username set to anything. By default, it needs to be set to "user" now.

**Comment by ufodone** [comment]
Ah, makes sense.  The authentication for the main connection doesn't actually require a user name so that never mattered with the old integration.  The new one also queries via the http port which does require a username.  Glad you got it sorted out!
