### ISSUE TITLE
Cannot have blank Alarm code to enable keypad v0.6.6 

### ISSUE THREAD

**Issue by Doughboy68** [ufodone/envisalink_new#38]
First time installing this.
FYI, the configuration did import from configuration.yaml after I renamed entry to envisalink_new.

However, I cannot enter a blank alarm code if one is entered... it retains the previous one.
Reason is I want the keypad to show, which will automatically do when there is no alarm code.
I tried putting a space in and did not work.

**Comment by Doughboy68** [comment]
To follow up on this more...

Seems to be the GUI does not accept blank input for the Alarm Code, and if nothing is entered in GUI it does not change the actual configuration to a blank code.

I got working by manually editing last line in core.config_entries to read just code"":  as below example, and have to restart HA (reloading it is not enough, yet when entering a code if code is blank and keypad shows in UI simply reloading removes keypad so that is a bit strange?!?)

*** BE VERY CAREFUL*** editing this file incorrectly can cause HA lovelace not to load at all and you will not even be able to restore a backup easily and have to recover some other way... I recommend installing ssh and samba to be able to remote in and make changes to revert if this happens... make a backup of the file in case! 

```
      {
        "entry_id": "7ca045295489861c0aaa43be93cdc59d",
        "version": 1,
        "domain": "envisalink_new",
        "title": "Alarm",
        "data": {
          "host": "192.168.21.210",
          "user_name": "user",
          "password": "user",
          "partition_set": "1",
          "zone_set": "1-8",
          "port": 4025,
          "discovery_port": 80,
          "evl_version": 4,
          "panel_type": "DSC",
          "code": ""
        },
```

**Comment by ufodone** [comment]
I've published a new [release](https://github.com/ufodone/envisalink_new/releases/tag/v0.6.7) which should fix the issue.
