### ISSUE TITLE
Window sensors triggering fire alarm code

### ISSUE THREAD

**Issue by jmunchies1** [ufodone/envisalink_new#44]
I have a Honeywell Vista 48p with a few built in sensors, mostly door and motion, just 5 zones.   I have it full integrated into HA with envisalink_new and it seems to be working correctly with the proper zones configured.  If I open a door while the system is armed, it activates as expected and the monitoring station gets the alarm has been triggered.

I don't currently have any built-in window sensors.  I bought some Ubiquiti Protect sensors that can act as windows sensors and have them integrated into Protect and HA (they are binary sensors).

I created an automation to trigger the alarm when a window sensor is opened.  The problem is, when I open the window, the alarm triggers however it's triggering as a Zone 96 Fire Alarm.  I don't have a zone 96, so I think the panel is getting confused with this device trigger since it's not actually attached to the panel.  Of course I want this to trigger as a regular intrusion alarm on the panel.  I can't find any documentation on how to adjust the type of alarm that's triggered (panic, fire, police? etc...) in the documentation.  Is this possible to do with the envisalink_new integration?  Sorry if I'm asking in the wrong spot, I don't know if this is actually an issue with the integration or if there's something else in HA I'm not doing correctly.  Thanks for any help!

Edit:  I am using alarm_trigger service in the automation for alarm_control_panel entity to trigger the alarm.  I did confirm I have Police set as panic type in envisalink_new.

**Comment by jmunchies1** [comment]
Quick update on this:  As I workaround, I've switched from using the alarm_trigger service to the envisalink_new.alarm_keypress service.  With this, when the Protect Window sensor opens, I have the automation send a B code to the physical alarm keypad which triggers the Zone 99 Police panic type.  That does seem to trigger the alarm correctly.

I did confirm that I have panic_type set to Police in envisalink_new but the added sensors don't seem to trip that when using the alarm_trigger service but the alarm_keypress service is a workaround.

**Comment by ufodone** [comment]
The `alarm_trigger` service maps the panic types as follows:

```
Fire -> A
Ambulance -> B
Police -> C
```

So your initial use of `alarm_trigger` was likely sending an `A` code while as your current setup is sending explicitly sending a `B` code.

I have a DSC system myself so am not familiar with the Honeywell panels but perhaps it's possible that A, B and C can be programmed for different meanings and the mapping above is based on what the original code author's system was setup as?

**Comment by jmunchies1** [comment]
> The `alarm_trigger` service maps the panic types as follows:
> 
> ```
> Fire -> A
> Ambulance -> B
> Police -> C
> ```
> 
> So your initial use of `alarm_trigger` was likely sending an `A` code while as your current setup is sending explicitly sending a `B` code.
> 
> I have a DSC system myself so am not familiar with the Honeywell panels but perhaps it's possible that A, B and C can be programmed for different meanings and the mapping above is based on what the original code author's system was setup as?

Thanks for responding and for your work on this!  Yeah I'm assuming the installer setup the ABC codes differently, which is fine I don't really need to change them (I don't have the Installer code anyway and can't reset it.  I can do a decent amount with the Master code though).

Is it possible to change the code in HA that alarm_trigger sends to the panel since it's defaulting to A?  I tried inputting 'B' for data in the yaml with alarm_trigger but then the automation fails to run.

**Comment by ufodone** [comment]
If you set the "Panic Type" configuration option to "Ambulance", then `alarm_trigger` should use `B`.  

If you are configuring the integration via the UI, you can find that option in the `Advanced` portion of the config.  If you are  doing it via configuration.yaml, then set `panic_type` to `Ambulance`.

**Comment by jmunchies1** [comment]
> If you set the "Panic Type" configuration option to "Ambulance", then `alarm_trigger` should use `B`.
> 
> If you are configuring the integration via the UI, you can find that option in the `Advanced` portion of the config. If you are doing it via configuration.yaml, then set `panic_type` to `Ambulance`.

That worked, thank you for the suggestion!
