### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by qwik3r** [ufodone/envisalink_new#56]
I'm receiving an error that says "failed setup, will rery" after configuring: https://share.zight.com/RBuzq0dL I don't quite know how to format the zones here so perhaps that is why? https://share.zight.com/12uQNEDL. (Just a heads up that i purposely left out the host and pin in the screenshot).

What am I doing wrong?

Thanks.

**Comment by qwik3r** [comment]
Just wanted to provide and update. I was able to call the service remotely from HA and arm/disarm so at lesat I know it's working. Just confused about the error above. Any help would be great, thanks.

**Comment by ufodone** [comment]
Have you checked the logs to see if there are any warnings or errors?

It's odd that you're able to arm/disarm with it in that state.  Have you disabled the stock `envisalink` integration by commenting the section out in your configuration.yaml and restarting HA?

**Comment by qwik3r** [comment]
Am I supposed to also configure the yaml file to add the zones there? 

e.g. 

envisalink_new:
    host: 
    panel_type: HONEYWELL
    user_name: 
    password: 
    evl_version: 4
    partitions:
        1: 
            name: "Home Alarm"
    zones:
        1:
            name: "Zone 1"
            type: "door"

**Comment by qwik3r** [comment]
Am I supposed to also configure the yaml file to add the zones there?

e.g.

envisalink_new:
host:
panel_type: HONEYWELL
user_name:
password:
evl_version: 4
partitions:
1:
name: "Home Alarm"
zones:
1:
name: "Zone 1"
type: "door"

**Comment by grunthos503** [comment]
Yes, put in the zone list as 1-24. No, don't add the zones into the YAML.  


I have to reload the integration for changes to take effect, and at least once I had to restart HA completely to see results.  Make sure you try that.

**Comment by qwik3r** [comment]
> Yes, put in the zone list as 1-24. No, don't add the zones into the YAML.
> 
> I have to reload the integration for changes to take effect, and at least once I had to restart HA completely to see results. Make sure you try that.

Thanks. I had 1-24 in there originally, reloaded the integration and didn't do anything. I also reloaded yaml didn't do anything but I don't recall if I restarted HA. I'll try that now. 👍

**Comment by grunthos503** [comment]
> another partition

That has to be changed in the alarm panel's configuration. I'm using DSC so I don't know how in Honeywell, but a quick web search will probably tell you how to remove an unneeded partition.

> Zone labels

Just rename in HA GUI like any entity-- click on entity to see status pop-up window, then click gear to edit.  Fill in the Name field with the new name. You can also set an HA Area there too.

**Comment by qwik3r** [comment]
Thank you so much! You're the best!

**Comment by qwik3r** [comment]
Hello again. I'm still having a bit of an issue. For whatever reason it's saying that my alarm is disarmed in HA when it is not: https://share.zight.com/GGuyrqnz. I can arm/disarm just fine through the Eyezon website and when I open a door the sensor updates in HA but I can't arm the alarm. I've tried several times. Any assistance would be great.

**Comment by ufodone** [comment]
That image shows that partition 3 is Disarmed.  You previously mentioned that you only have one partition.  Does the alarm control panel entity for partition 1 also show the incorrect state?

It's odd that partition 3 is showing up unless you've explicitly configured it.  In the `Configure->Basic` settings for the `envisalink_new` integration, is your `Partition List` setting just set to `1`?

**Comment by qwik3r** [comment]
> That image shows that partition 3 is Disarmed. You previously mentioned that you only have one partition. Does the alarm control panel entity for partition 1 also show the incorrect state?
> 
> It's odd that partition 3 is showing up unless you've explicitly configured it. In the `Configure->Basic` settings for the `envisalink_new` integration, is your `Partition List` setting just set to `1`?

Hello. Actually it says "partition list: 3" in that section. I assume that should be listed as 1?

**Comment by ufodone** [comment]
That list should match the partitions that your alarm panel has configured.  In most cases I've seen, it should just be `1` - which also matches the example yaml config you posted earlier.  Partition 1 is typically the default partition on these systems and the partition used for arming/disarming the entire system.

**Comment by ufodone** [comment]
You could also try configuring a range of partitions (e.g., `1-3`) if you don't know which ones are active on your alarm system.  You could then arm/disarm the alarm from a physical keypad and see which of the partitions in HA reflect the actual alarm state.  Once you've narrowed down which partitions are relevant, you can reconfigure just those partitions.

**Comment by qwik3r** [comment]
> You could also try configuring a range of partitions (e.g., `1-3`) if you don't know which ones are active on your alarm system. You could then arm/disarm the alarm from a physical keypad and see which of the partitions in HA reflect the actual alarm state. Once you've narrowed down which partitions are relevant, you can reconfigure just those partitions.

Thank you!

**Comment by qwik3r** [comment]
So just a quick update. I didn't put the 1-3 which I now believe pertains to each keypad, but rather just put '1' under partitions and that worked -- however, using the 'switch' on the dashboard to go from armed 'home' to 'away' does NOT work. The switch will allow me to disable the alarm and THEN enable 'away' but I can't go from home - > away without first disabling. It switched itself back to 'home' after a period of time when I tried. Is this normal behavior?

**Comment by ufodone** [comment]
I've always assumed that the panels couldn't transition between two different arming states and always needed to go to disarmed first but I'll be honest that I haven't tried.  Does your physical alarm panel allow this transition?

The arm home and arm away buttons in HA just cause the integration to issue the `*<code>3` and `*<code>2` keystrokes respective to the panel respective.

**Comment by qwik3r** [comment]
> I've always assumed that the panels couldn't transition between two different arming states and always needed to go to disarmed first but I'll be honest that I haven't tried. Does your physical alarm panel allow this transition?
> 
> The arm home and arm away buttons in HA just cause the integration to issue the `*<code>3` and `*<code>2` keystrokes respectively to the panel.

I have to give it a try. 

On another note, because I often have the doors open during the day in HA the log book is filled with a ton of "FRONT DOOR FAULT 20" etc logs indicating that something is open. Is there anyway to cull these down? I'm just concerned it might affect HA's performance with constant logging.

**Comment by ufodone** [comment]
Are those logbook entries adjacent to each other or are there other entries from the keypad in-between them such as a similar entry for a motion detector, etc.?  

The entries are being generated whenever the Envisalink sends a state update.  Those particular entries are from the virtual keypad updates which reflect the current message displayed on physical keypads.  Because Honeywell keypads cycle through displaying all the currently faulted zones, you will see regular updates like this in your logbook.  I thought HA would suppress ones where the state hasn't actually changed though  which is why I ask whether you see multiple of the same updates adjacent to each other.

If you are concerned about HA's performance and don't care about the updates, you could configure the HA [Recorder](https://www.home-assistant.io/integrations/recorder/) to exclude them.

**Comment by qwik3r** [comment]
> Are those logbook entries adjacent to each other or are there other entries from the keypad in-between them such as a similar entry for a motion detector, etc.?
> 
> The entries are being generated whenever the Envisalink sends a state update. Those particular entries are from the virtual keypad updates which reflect the current message displayed on physical keypads. Because Honeywell keypads cycle through displaying all the currently faulted zones, you will see regular updates like this in your logbook. I thought HA would suppress ones where the state hasn't actually changed though which is why I ask whether you see multiple of the same updates adjacent to each other.
> 
> If you are concerned about HA's performance and don't care about the updates, you could configure the HA [Recorder](https://www.home-assistant.io/integrations/recorder/) to exclude them.

Basically I think it's just reporting on the status as it cycles through on the keypad. If i'm in front of the keypad it cycles through "20, 9, 7" etc to indicate the "faulted" (open) zones. 

There are hundreds, probably thousands of these in the log: https://share.zight.com/NQu5Kbbp

**Comment by qwik3r** [comment]
So I tested if you could switch modes via the app and you cannot. You have to disarm first. I guess it's a bit misleading with the UI in HA since the switch lets you go from one to the other, it should perhaps not allow that until you disarm it first. 

On another note, I tripped my power today and my router went out, upon it coming back up the Envisalink integration ceased to work. I have tried restarting it several times, plugging/unplugging the Envisalink in the panel and restarting HA to no avail. 

I tested if it's working via Eyezon's site and it indeed is, so there is a connection. Do I have to remove the integration and start again? Could the IP to the device have changed and maybe that's why (since the router restarted).

Thanks.

**Comment by ufodone** [comment]
> Basically I think it's just reporting on the status as it cycles through on the keypad. If i'm in front of the keypad it cycles through "20, 9, 7" etc to indicate the "faulted" (open) zones.

Okay, that's normal behaviour then.  The logbook is just reflecting the valid state changes of the keypad.  You should use HA's Recorder exclusion list to suppress them if you don't want them filling up the logbook.

>I guess it's a bit misleading with the UI in HA since the switch lets you go from one to the other, it should perhaps not allow that until you disarm it first.

This is likely a behaviour of the alarm control panel entity in HA rather than anything specific to this integration.  It's possible that some alarm panels can handle this transition.  I don't know if there's any way to override this behaviour.

> On another note, I tripped my power today and my router went out, upon it coming back up the Envisalink integration ceased to work. I have tried restarting it several times, plugging/unplugging the Envisalink in the panel and restarting HA to no avail.
>
> I tested if it's working via Eyezon's site and it indeed is, so there is a connection. Do I have to remove the integration and start again? Could the IP to the device have changed and maybe that's why (since the router restarted).

You definitely should not need to remove the integration and start again.  It's certainly possible that the router assigned a new IP address when the power was restored.  If that's the case, you should be able to go into `Settings -> Devices & Services -> Ensisalink_new` and then click the `Configure` button and change the IP/host of your device in the `Basic` settings once you've figured out what the new IP is.

Have you checked the logs for errors?

**Comment by qwik3r** [comment]
Thank you. Regarding the UI, I figure that was the case. It's not a big deal just something I noticed, all good. 

How would I determine what the IP of the Envisalink is now? I would imagine that if I can connect to it via Eyezon's site that might not be the case or am I mistaken? 

Not really sure where to look in the logs. All I see when hovering over the integration that says "failed setup, will retry" is "unrecognized panel type at 192.xxxx. etc".

Nothing else has changed with my setup, or settings with ADT or anything other than the power going out with the router.

**Comment by grunthos503** [comment]
> How would I determine what the IP of the Envisalink is now?

Look at your router's DHCP client list.  Or you can look in your Eyezon account; you will see "local IP address" under details.  The Eyezon service works fine when the Envisalink changes address, because the Envisalink is initiating the connection to Eyezon, so Eyezon doesn't know or care about the address of your Envisalink.

To avoid this issue with HA, in your router DHCP client list, configure your Envisalink with a static IP address.

**Comment by qwik3r** [comment]
> How would I determine what the IP of the Envisalink is now?
> Look at your router's DHCP client list. Or you can look in your Eyezon account; you will see "local IP address" under details. The Eyezon service works fine when the Envisalink changes address, because the Envisalink is initiating the connection to Eyezon, so Eyezon doesn't know or care about the address of your Envisalink. To avoid this issue with HA, in your router DHCP client list, configure your Envisalink with a static IP address.

Thanks! It looks like the iP did indeed change when the router rebooted 😡 so I'll have to fix that.

**Comment by qwik3r** [comment]
Had a few more questions (hope you don't mind!)

1. Is there a way to arm the alarm in an automation without putting the code in a field, such as if it was specified in a yaml file instead? 

2. When you use the 'arm' panel in HA if there's a fault it doesn't really tell you, it just disarms it. Is there anyway to create a card that would tell you "couldn't arm because of xyz" or is that more or less something I have to create as an automation that checks if each zone is 'closed' ?

**Comment by jhenkens** [comment]
@qwik3r 
1. Go to integrations -> Envisalink_new -> configure -> basic, and input your code. This will remove the keypad numbers from the Alarm Control Panel entity when displayed on dashboards, and also make services work without inputting the code.
2. I believe the general belief of HA is to expose sensors as provided by the underlying integration (i.e., the Envisalink itself), and to allow users to create helpers/UI elements as needed. You can make your own "arm alarm" script that first checks if the `sensors.keypad` is displaying "Ready", and if not, put a persistent notification up in HA (or whatever you want) to alert why the Alarm couldn't arm.

**Comment by qwik3r** [comment]
> @qwik3r
> 
> 1. Go to integrations -> Envisalink_new -> configure -> basic, and input your code. This will remove the keypad numbers from the Alarm Control Panel entity when displayed on dashboards, and also make services work without inputting the code.
> 2. I believe the general belief of HA is to expose sensors as provided by the underlying integration (i.e., the Envisalink itself), and to allow users to create helpers/UI elements as needed. You can make your own "arm alarm" script that first checks if the `sensors.keypad` is displaying "Ready", and if not, put a persistent notification up in HA (or whatever you want) to alert why the Alarm couldn't arm.

Thank you!
