### ISSUE TITLE
Question: What happens if Alarm is not ready to Arm?

### ISSUE THREAD

**Issue by peros550** [ufodone/envisalink_new#58]
Is it possible to expose an entity , something like isReadyToArm that would be true if the Alarm is ready to Arm?
(sorry if this is already implemented, I have lost my remote access and need to wait for a week before I get back home and check)

**Comment by grunthos503** [comment]
You can implement your own by creating a template helper binary_sensor entity.

You can get the state from 

> sensor.alarm_partition_1_keypad

If the state is "Ready", you are fully secure and ready for either stay or away arming.

If the state is "Ready - Force Arm", you are externally secure and ready for stay arming.

Any other state is not ready for arming.
