### ISSUE TITLE
Update entity availability based on whether successfully connected to the EVL

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#7]

**Comment by rct** [comment]
I've noted the old (current) integration gives no clues if it loses connection to the Envisalink. So this would be very much appreciated.

Do you have ways of testing this?

**Comment by ufodone** [comment]
I've been slowly piecing together a mock EVL server that I can use to test against and so I'll be able to use that to test losing connection.

**Comment by rct** [comment]
Any chance you can share your mock EVL server?   I've been thinking about cobbling something together for a while.

Right now, I want to test the bug I saw with the 1.5.203 firmware where the envisalink kept sending 67302, 67303, 67304, about 10 times a second, which caused an unexpected recursion problem in AlarmServer - https://github.com/juggie/AlarmServer/issues/78

**Comment by ufodone** [comment]
Sure, I just committed what I have to my [pyenvisalink branch](https://github.com/ufodone/pyenvisalink/tree/command_queuing).

It's pretty basic right now and doesn't do much to actually simulate real behaviour but it should at least be flexible enough to hack together what you're trying to simulate.  That's mostly what I've been using it for myself at this point.  

You just need to set some variables at the top of evl_mock.py to set the panel type and password and then run it.
