### ISSUE TITLE
Feedback on binary sensors wonky when multiple are active

### ISSUE THREAD

**Issue by ddetton** [ufodone/envisalink_new#70]
One issue I am seeing is when I open a single door and close it, the button card for that sensor activates when the door is open and deactivates when I close it.  But if I open a door without closing it, then open another door, feedback for the second door is delayed several seconds before it activates.  Then if I close the first door while leaving the second door open, feedback for the first door stays activated until I close the second door.  Once the second door is closed, both sensors are deactivated.   I am using mushroom entity cards for the sensors and they are all inside a grid card.  Tried this with the packaged component and I get slightly different behavior.  In packaged component, the feedback is delayed longer.

**Comment by ufodone** [comment]
I'm guessing that you have a Honeywell panel?  If so, this is likely just an artifact of how those panels behave.  You can read up on some details in #45.  If you have a DSC system or you think your situation is different, let me know.

**Comment by ddetton** [comment]
Thanks for getting back to me on this. I looked at the dialog in the other issue you pointed me to and that makes sense.  I have controlled and monitored the Vista 128bpt (my panel) from a Creston system using an onboard RS232 serial connection.  Someone else originally wrote the software and I found it to be very sluggish, taking up to 8 seconds to report changes in state.  After digging into the code, I found that it was checking for changes every second.  But each second it would check a different partition.  Since there are 8 partitions on this panel, it could take 8-9 seconds to get feedback.  I changed the code so that when the user was on the security panel page, I would check state 8 times per second so it would only take a second to catch changes in state.  When the user was not on the security page, I just reverted back to once per second.

I don't know if you are dependent on what Envisalink makes available to you or if you can query the system for state changes more frequently.  I'm going to look closer at the envisalink web interface to see if changes in state get updated more frequently than what I am seeing.  Stay tuned.

**Comment by ufodone** [comment]
I don't have a Honeywell system myself so I'm not sure what text you are referring to that might be parsable but it's possible that's already taken into consideration.  The zone open/closed logic is already based on the (virtual) keypad updates.  While it doesn't parse the text, the updates from the Envisalink do include the zone number alongside the text to be displayed and that is used to make the updates.

What specific text updates are you referring to that you think might be usable?

Separately, a technique others have used to help speed the updates up is to move motion zones to a separate partition (as described [here](https://github.com/ufodone/envisalink_new/issues/9#issuecomment-1430741287)).  I don't know if that would help in your situation or not.
