### ISSUE TITLE
I installed lates HACS update for invisalink_new and all sensors became upavailable.

### ISSUE THREAD

**Issue by wptracy** [ufodone/envisalink_new#72]
I installed latest HACS update for invisalink_new and all sensors became unavailable.

how do i go back to the old release.  I didn't do a backup before I installed v0.7.3

I found I had to open/close all doors and window, activate the motion sensor, and open the water detectors to clear the unknown states of the sensors.

![Screenshot 2023-12-01 at 14-39-16 Overview – Home Assistant](https://github.com/ufodone/envisalink_new/assets/78648145/d31123ca-0e02-445d-9ace-e992c82a14cc)

**Comment by ufodone** [comment]
Sorry about that.  I've published a new release which I think will fix the issue.

**Comment by wptracy** [comment]
Thanks ufodone

**Comment by wptracy** [comment]
ufodone, the new release v0.7.4 does not show up in the HACS.

How do I have HACS check for updates, or how do I install it from https://github.com/ufodone/envisalink_new/releases/tag/v0.7.4

**Comment by ufodone** [comment]
If you go into HACS and click on the `Envisalink Refactored` integration, then click the three dots in the upper right corner and choose "Redownload".  It should give you an option to choose the version to download.  If it still isn't showing there, you might need to choose the "Update Information" option first.
