### ISSUE TITLE
Question: System Loss of Power report on Logbook

### ISSUE THREAD

**Issue by peros550** [ufodone/envisalink_new#75]
I was having some power outages recently, and wanted to know how many happened in a short period of time. Hence my question,  could it be possible that this integration logs in HA when power loss happened? The alarm system is a perfect probe for this kind of information.  Obviously, HA,  and LAN would need to run on UPS so that when system loses power, HA would still be reachable to receive messages.

**Comment by grunthos503** [comment]
Yes. AC Present is reported as an entity in HA.  I see it's history status in mine, so it does what you ask.

**Comment by peros550** [comment]
@grunthos503 are you sure this is exposed from this intergration? I don't seem to have it. My panel is a DSC1616 with Envisalink-3 board.

**Comment by grunthos503** [comment]
Oops, sorry, I forgot that I had to create the entity.

The information is there in the integration, as an attribute of the keypad. If you want it as a separate entity, you need to create a binary_sensor template containing

{{ state_attr('sensor.alarm_partition_1_keypad','ac_present') }}

That will allow you to keep history and display on dashboard or use in automations.

**Comment by peros550** [comment]
Hi thanks for the help, I set up and it’s new binary_input status is “off”. Any idea how to troubleshoot further ?

**Comment by grunthos503** [comment]
Go to Developer Tools -> States and filter for your keypad entity. See if it has AC present as an attribute.  If it does, then you need to fiddle around with the template.  If it's not there in the attributes, then you're out of luck.  

(I have a DSC 1864 with EVL 4.)
