### ISSUE TITLE
Separate address for discovery

### ISSUE THREAD

**Issue by rhatguy** [ufodone/envisalink_new#79]
I have previously used the built in envisalink integration with a java based DscServer
https://sites.google.com/site/mppsuite/downloads/dscserver-2?authuser=0

DscServer is basically a proxy for the envisalink TPI, which allows multiple clients to connect.  The envisalink is still accessible on port 80, however all access on 4025 is pointed at the DscServer.  The way the addon currently works, it is unable to connect to the envisalink on port 80 and then route its TPI connectivity to a different IP address.

Would it be possible to split the IP for the TPI connectivity and the IP for discovery into two separate variables/inputs?

**Comment by ufodone** [comment]
I have added [support](https://github.com/ufodone/envisalink_new/commit/699a79526648aee01de07fab1d7a420c3f3bc57e) for this.  It isn't in an official release yet but if you can install the `main` version to try it out.

You can specify the `Discovery Port` config as `hostname:port`.

**Comment by ufodone** [comment]
Released in [v0.8.0](https://github.com/ufodone/envisalink_new/releases/tag/v0.8.0).
