### ISSUE TITLE
Omit password and alarm code from debug logs

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#8]
Debug logs currently will log the EVL password and alarm code.  Update the logging to ensure those values are scrubbed to make it simpler and safer to users to post logs to public forums.

**Comment by sheyman1** [comment]
How do I update the logging to ensure those values are scrubbed?

**Comment by ufodone** [comment]
You don't need to do anything on your side.  It will automatically omit the password and alarm code from any debug logging.  The only exception is if you send an explicit keypress sequence (e.g. via an HA service call) that includes the code but I expect that would be rare.

**Comment by ufodone** [comment]
These changes are in the v0.4.0 release.
