### ISSUE TITLE
code_arm_required is defaulted to true

### ISSUE THREAD

**Issue by theBasher91** [ufodone/envisalink_new#84]
Hi there, 

If code_arm_required = true, you are required to enter a code to arm it via voice (i.e. via google assistant). A code is not needed if code_arm_required is set to false.

The default value with this integration is true. IS there a way to include a way to customize this on setup so that its permanent? OR must I manually set the attribute state every time?

**Comment by ufodone** [comment]
Would it be sufficient for the integration to set this attribute based on whether you have configured a code in the settings?

**Comment by theBasher91** [comment]
That would be great!

**Comment by ufodone** [comment]
Added in v0.8.1
