### ISSUE TITLE
feature request: also expose "fault" zone attribute as state entity

### ISSUE THREAD

**Issue by tinuva** [ufodone/envisalink_new#85]
As a follow up request on #63 

As an option, could the integration also expose "fault" zone attribute as a state entity?

This is the attributes I see:
![Screenshot 2024-01-17 at 14 25 17](https://github.com/ufodone/envisalink_new/assets/5417682/dd9a0924-c595-428f-be3a-311c47bcb0e5)

My use case is as follow. I have conditional mushroom chips, that only show up when the entities is _not_ in a certain state. What I want to do is, if any of my zones have a fault, or low battery, I want a chip to show up the issue.

For example, when I configure the chips these are all of them:
![Screenshot 2024-01-17 at 14 24 52](https://github.com/ufodone/envisalink_new/assets/5417682/664eb261-6670-4637-b2b8-9a7db6bd53ef)

But only the ones not in a specific state show up. For example currently, with open zones, the keypad is in a "Not ready" state. I hide this chip when the keypad is in the "Ready" state.

![Screenshot 2024-01-17 at 14 25 01](https://github.com/ufodone/envisalink_new/assets/5417682/a85e51e5-e6e5-4ee0-a255-67d92d84333e)

These chips, do not support conditions based on attributes.

**Comment by ufodone** [comment]
I've added this to the v0.8.0-beta3 release.

**Comment by tinuva** [comment]
Sweet, can confirm I see them. This will now make life so much better :)

Thank you for the excellent work!

**Comment by ufodone** [comment]
Released in [v0.8.0](https://github.com/ufodone/envisalink_new/releases/tag/v0.8.0).
