### ISSUE TITLE
binary_sensor.panel_health update issue

### ISSUE THREAD

**Issue by disforw** [ufodone/envisalink_new#87]
Panel connected: Vista 21IP
Release version: 0.8.0

when a zone is in trouble, wireless smoke low battery, the new health binary_sensor keeps toggling on and off every 3 seconds.

**Comment by ufodone** [comment]
Can you provide a bit more detail?  What do you mean by a zone being in trouble and what does "wireless smoke low battery" refer to?  

Wireless zones sensors are only supported on DSC systems.  Does "smoke" refer to the panel's new "Fire" entity and does "low battery" refer to the panel's "Battery Health" entity?

**Comment by disforw** [comment]
![IMG_3583](https://github.com/ufodone/envisalink_new/assets/24241104/24366d9c-4b90-423b-a138-645db4a42119)

zone turning on/off every few seconds..

**Comment by disforw** [comment]
I was just using an example, it’s any panel/zone trouble.

**Comment by ufodone** [comment]
Is it just the panel health entity that is toggling?

Can you turn on debug logging and capture this happening so I can see what's going on?  I don't have a Honeywell system that I can test this wth.

**Comment by franquosino** [comment]
I have the same Vista panel and have a similar issue, although logging a different fault. Note that I didn't re-configure the integration when I simply updated from v0.7.4 to v0.8.0. In summary, when one of my (wired)  sensors detects motion, the same zone triggers a detected gas fault. I haven't checked if it's the case for all zones, but for sure with motion sensors. 

I'm attaching part of a regular log, but also a debug log  section on this integration. Hope that helps.

![Screenshot 2024-01-23 095908](https://github.com/ufodone/envisalink_new/assets/31945267/fa05c155-ac80-4fd9-974c-993eac18c904)
[home-assistant_envisalink_new_2024-01-23T02-25-57.765Z.log](https://github.com/ufodone/envisalink_new/files/14028275/home-assistant_envisalink_new_2024-01-23T02-25-57.765Z.log)

**Comment by ufodone** [comment]
@franquosino The "gas detected" is just an artifact of me trying to choose a "Show As" type for the new fault entity that used meaningful language (rather than True/False).  I didn't realize that it would show up as "gas detected" in the logbook.  I'll change it to something different.

It also appears that on Honeywell panels, it may not be properly differentiating between a zone "opening" vs "faulting" so both the main zone binary_sensor and the new "fault" one just mirror each other.  I'll have to see if there's a way to differentiate for Honeywell.

I don't think this is related to the original issue though as that is referring to entities for the panel itself rather than for specific zones.  Looking at the log file you attached, I also don't see the "trouble" flag toggling on/off as reported by @disforw.

**Comment by franquosino** [comment]
In light of the fact that those binary sensors entities are primarily for DSC panels, would you see as advisable to disable them when connected to a Honeywell panel? Unless there is a chance that they may work in the future, I don't see the point in keeping those entities active.

**Comment by ufodone** [comment]
Yes, from what I can tell, it doesn't look like the Honeywell panels provide enough info to accurately represent the fault state so I'll change it so it doesn't create them.

**Comment by franquosino** [comment]
Ok, thank you. If you're going to make the change so that those entities don't get created for the Honeywell panels in the integration, then I won't bother disabling them individually.

**Comment by disforw** [comment]
Hang on a sec. I like the direction of the new binary_sensors and would like to keep them if possible, allow me a little time to look in to this further?

**Comment by ufodone** [comment]
To be clear, I'm only removing the zone-specific "fault" entities as they currently only reflect the main zone binary_sensor entities on Honeywell systems.  If a zone is showing as open, it will also show as fault and vice versa so it doesn't add any value.  TBH I'm not even sure what the "fault" should represent on Honeywell.  Looking again at the DSC TPI documentation, there are separate "in alarm", "tamper', "fault", and "open" events (of which the current fault entities maps to the "fault" event) but I don't know what triggers a "fault" in this case.  I originally thought it was when a zone was tripped while the alarm was armed but I'm guessing that the "in alarm" event is meant for that.

I've left the panel entities in place (panel health, battery, AC present, etc.) as those should be working fine.

It's still unclear to me though why you are seeing the panel health entity flapping every three seconds.  A debug log file would likely reveal the cause.

**Comment by disforw** [comment]
OHHH, yes I agree, on Honeywell the “fault” zones are redundant.

I am looking at the panel health zone.
