### ISSUE TITLE
Update zone timer dump algorithm

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#9]
DSC and Honeywell systems seem to report zone timer dump data differently.  

DSC systems seem to report accurately based on the documentation.
Honeywell systems still report a zone having been closed for up to 3 ticks even when it is still open.

The original code here treated both systems the same and anything less than 5 ticks (30 seconds) was considered open.

Update the processing to account for these differences:
- For DSC: only report a zone open when ticks == 0
- For Honeywell: If an explicit zone update has been received since the last zone dump, then honour the current state.  Otherwise, treat a zone as open if ticks <= 3.

**Comment by ufodone** [comment]
@sheyman1 @jl-678

I have committed some changes which I hope will address the issue you are seeing with the zones flapping.  I haven't published a release with them yet but would appreciate if you'd be able to give them a shot and see if they address the issues are you seeing.  

You can grab these changes by updating your `envisalink_new` version via HACS:

1. Go to HACS->Integrations->Envisalink Refactored
2. Click the 3 dots in the upper right hand corner of the screen and select "Update Information" followed by "Redownload"
3. Select the "main" version in the dropdown (it should be at the bottom).
4. Restart HA

I had to speculate a bit on the fix based on what I've seen in the logs you provided and that I've seen from others.

**Comment by sheyman1** [comment]
Silly question, but how do I install this to test your version?  I tried
following:  Configuration of the integration has been upgraded to use HA's
config flow (via the UI). To add an envisalink device, go to Settings ->
Devices & Services, click Add Integration at the bottom left of the screen
and search for envisalink_new.

But envisalink_new doesn't show up as an option when searching under add
integration?

Thanks

**Comment by ufodone** [comment]
Ah, I thought you'd maybe already gotten setup with this version.

Do you have HACS setup already?  If so, you need to first install this integration there by clicking into HACS link via Home Assistant and then clicking the 3 dots in the upper right corner and selecting "Custom Repositories".  From there, past in `https://github.com/ufodone/envisalink_new/` as the repository and choose `Integration` for the category.

Once you've done that and restarted Home Assistant, you should be able to add a new device under Settings->Devices & Services.  However, since you already have your configuration in configuration.yaml, you should just need to rename "envisalink:" to "envisalink_new:" in your configuration.yaml and restart HA.  It should automatically import that configuration and you will see the device under Settings-> Devices & Services.

Once you're up and running, you can then follow the instructions I posted earlier to download the "main" version.

**Comment by sheyman1** [comment]
I think I'm getting closer but not installed yet.  Yes, I do have HACS.  I
added the custom repository as integration but that's as far as I get.
Envisalink_new isn't showing up in HACS or settings, devices & services add
integration?  Also if I change my config from envisalink: to
envisalink_new: when I check config it says error on that line
envisalink_new not found.  I tried to add the custom repository link again
but HACS says it already exists in the store?

**Comment by ufodone** [comment]
It's been a while since I did this but it's possible that now that you have the repository added, you need to click the "+ Explore and Download Repositories" button in HACS and actually install `envisalink_new`.

**Comment by sheyman1** [comment]
Thank you.  I was able to get it working by following your instructions.
Was just about to email you that the zones weren't updating but just saw
your update and installed v0.4.1 and all seems to be working ok now.  Great
job, thanks for all that you are doing with this.  It's about 30 degrees
here tonight so I will test the zone flapping tomorrow mid day when it's
warmer and will report back.

Scott

**Comment by ufodone** [comment]
>Envisalink_new seems to be working ok for me except that the open zone flapping is still happening just as before. My config shows the following for logging to try to help you. Attached is the log, I restarted then opened around 5 doors / windows. Let me know what else I can do to help with this...
Thank you

Sorry to hear that the changes didn't fix the issue.  Unfortunately the log file you posted doesn't have the debug logs because this integration name is different.  To get the debug logs, you'll need this instead:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```

Would you be able to run a test again with this logging on?

**Comment by sheyman1** [comment]
[home-assistant_2023-01-30T22-59-49.351Z.log](https://github.com/ufodone/envisalink_new/files/10540693/home-assistant_2023-01-30T22-59-49.351Z.log)

I restarted HA then opened 3 windows and 1 door.  I believe when the 4th device is opened the flapping starts.  For the duration of this test those 4 devices were never physically closed but you should see in the log that they randomly show closed then open then closed, etc.  Let me know what else I can do to help...
Thanks
Scott

**Comment by ufodone** [comment]
Thanks, I'll take a deeper look tonight.  If it's not too much trouble, it would also be helpful to get another test but with the zone timer dump interval set back to 30 seconds.

**Comment by sheyman1** [comment]
Here is the same test with the zone_dump set to 15.
[home-assistant_2023-01-30T23-33-10.581Z.log](https://github.com/ufodone/envisalink_new/files/10540873/home-assistant_2023-01-30T23-33-10.581Z.log)

**Comment by sheyman1** [comment]
Here is the same test with the zone_dump set to 30.  (disregard the motion detectors in all these tests)
[home-assistant_2023-01-30T23-39-56.015Z.log](https://github.com/ufodone/envisalink_new/files/10540917/home-assistant_2023-01-30T23-39-56.015Z.log)

**Comment by ufodone** [comment]
Well, the good news is that the logs gave me a better idea of what's going on.  The bad news is that I think it's either a bug in the firmware or a limitation of the  Honeywell systems.  

After the four non-motion zones are opened, I can see that one of them will report as closed for a bit and then report as open again.  This seems to coincide with an additional zone opening - in this case a motion zone (or two) triggering.  During this time it looks like the keypad updates also stop reporting the zone as open.  

According to the TPI documentation, Honeywell systems don't do a great job of reporting zone status.  Based on this, one theory I have is the the zone status updates are actually derived from the keypad updates but the keypad itself will only ever report a maximum of 4 open zones (maybe the most recently faulted?).  And so once an additional zone is opened, the zone status updates will only show 4 of them open which will caused the envisalink integration to show it as closed.  

I'd be interested in knowing if is a "limit of 4" problem or whether there's something unique about the motion zones.

If possible, I'd love to get two additional sets of logs:

1. Open the same four zones but avoid triggering any of the motion zones.  I don't know if this is feasible given your house and zone layout.
2. Open the same four zones but then also an additional one.  

A 30 second zone timer dump would be fine for these tests.

Based on the results, it might be possible for me to put something in to compensate.  The downside might be that it takes longer to recognize when a zone is cleared (in cases where there are more than 4 zones open).

**Comment by philh30** [comment]
I've spent a good bit of time looking at Honeywell updates when I worked on the ST integration. I'm using your envisalink_new now so happy to help.

The Honeywell panels just report one faulted zone at a time every time the keypad message updates, and never provide a positive indication that a zone has been cleared. Keypad updates happen every 5-6 seconds, and the keypad cycles through the faulted zones in ascending order. A newly faulted zone is immediately reported, and then the cycle restarts at the lowest numbered zone that's faulted. Cleared zones just drop from the cycle. As an example, let's say zones 1, 4, 6, and 10 are already faulted, then zone 7 is faulted, then zone 4 is cleared. The keypad would show:

Zone 1 fault
Zone 4 fault
Zone 6 fault
Zone 10 fault
Zone 1 fault
Zone 4 fault
Zone 7 fault <---- newly faulted zone
Zone 1 fault <---- restart cycle after a new fault
Zone 4 fault
Zone 6 fault
Zone 7 fault
Zone 10 fault
Zone 1 fault
Zone 4 fault
Zone 6 fault
Zone 7 fault
Zone 10 fault
Zone 1 fault
Zone 6 fault <---- zone 4 is skipped because it has cleared
Zone 7 fault
Zone 10 fault

I've never really messed with the zone timer dumps, but my understanding is that the EVL just counts the number of keypad updates since a zone last appeared as faulted. Ideally, if n zones are faulted then each zone should show up every nth keypad update. However, newly faulted zones mess up that logic, and frequently faulted zones like motions are a real problem to try to interpret. If there are any other problems, such as a low battery in a wireless zone, then those warnings also get added to the cycle.

**Comment by ufodone** [comment]
This is great info, thanks!  The zone timers get reported very oddly on Honeywell systems and not at all how the TPI documentation states so I'll be interested to go back to the logs and see if your understanding explains what I've been seeing.

What you describe for the virtual keypad updates (%00) matches what I'd inferred.  What troubling me is the %01 zone state updates which seem to work fine with up to 4 zones faulted but then start "dropping" zones.  E.g. in your example, I'd see a %01 update indicated that zones 1, 4, 6, and 10 are faulted but then when zone 7 faults, I'd get another %01 update indicating that maybe 1, 6, 7, and 10 are faulted.  Eventually when 7 clears, 4 would start being reported as open again.

**Comment by philh30** [comment]
The %01 reports are generated by the EVL, and are probably just reporting zones with a timer <5. I don't know that I'd put any stock in them. The %00 reports are the "source material" direct from the alarm panel.

I'm looking at some of the zone timers from the first log that was posted above (where zone dump is set to 5 seconds) and they mesh with what I'd expect from the TPI docs. In the minute interval below, it looks like 2, 3, 11 and 14 are open for the duration. Motion zone 7 is tripped at 14:56:40 but then goes quiet. Best case, zone 7 would be marked clear at 14:57:00 when it's skipped in the pattern, but that might lead to false clears. If we just look at how high the zone timers get, I would want zone 7 to clear around 14:57:15 when the zone timer hits 8.

![image](https://user-images.githubusercontent.com/45735120/215897046-afbd3495-233c-4fa5-80fd-8ebd2137d411.png)

Speaking more generally, take the number of zones suspected to be open and add on a margin. Only mark a zone as clear when the zone timer exceeds that amount.

I don't see any partition 2 zones popping up in this small time period, and sheyman1 may not have any zones assigned there. Each partition has its own keypad update queue, so it's helpful to know which zones are assigned to which partition. In my own setup, I've shifted my motions to partition 2 to help with some of this zone flapping.

**Comment by sheyman1** [comment]
Thanks for all the info, very interesting.  The weird thing in my mind is that I thought the EVL was supposed to mimic another keypad.  I have a 6290w Honeywell touchscreen keypad and it seems to show zones faulted and cleared in near real time regardless of how many are open or how many motion events there are.  In other words, it seems to show actual faults in real time without any flapping ever.  I've also tried to watch the EVL web page for flapping and don't think I've noticed it there, but that doesn't seem to show changes very quickly. 

Tomorrow I will try to test again as suggested without tripping any motion and will upload the log when complete.  If there's anything else you would like me to try please let me know.

Thank you
Scott

**Comment by ufodone** [comment]
I'm guessing your physical keypad cycles through the faulted zones just like the virtual keypad updates that the EVL sends but it probably doesn't show you a "moment in time" snapshot of all the faulted zones?  And a keypad update is also sent when all zones are cleared (aka the partition is "Ready").  So if that's the case, then there isn't any need to know when a zone clears. 

But I think with this latest info provided by @philh30, I should be able to get things not to flap.

**Comment by ufodone** [comment]
@philh30 Do you happen to have any info on when the "USER/ZONE Field" in the %00 keypad update will represent a zone number?  Specifically in relation to the bit states of the LED/ICON Bitfield.  The one state I've seen (which makes sense) is when the Ready(12) bit is clear.  But I don't know what happens when, for example, the alarm is armed.

**Comment by philh30** [comment]
When both flags.not_used2 and flags.not_used3 are set it indicates a partition status update not related to a specific zone (battery flag in that case indicates the system battery instead of a zone battery). When those aren't set, the system could be reporting that it's counting down to arm (requires parsing the alpha field to verify). Otherwise, if USER/ZONE is numeric it's giving a zone update.

When a partition is armed it bypasses any zones not armed, so the only reports that come in for that partition are when the alarm sounds. When the alarm sounds, it follows the same logic as above as to whether USER/ZONE indicates the zone number or something else.

I'm trying to see if I can port the [keypad update handler from the ST driver](https://github.com/philh30/ST-Edge-Drivers/blob/9510c4ebc6d8a1a38380b8ee6bfa6f305403eb53/Honeywell/Envisalink-Vista/envisalink-honeywell-release/src/envisalink.lua#L387-L491) into Python. I had worked out the logic pretty well to handle zone status without needing the timer dumps.

**Comment by rct** [comment]
I realize the issue at hand is working around shortcomings in the panel/protocol.  My apologies if this is too much of a tangent for this topic, however if you need to see what the zone sensors are actually sending and when, an RTL-SDR with the rtl_433 software can capture the messages from most of the 5800 series wireless sensors.  rtl_433 outputs to MQTT, so that data is available to home assistant. 

```
{"time" : "2023-02-01 11:39:07.094123", "model" : "Honeywell-Security", "id" : 952xxx, "channel" : 8, "event" : 128, "state" : "open", "contact_open" : 1, "reed_open" : 0, "alarm" : 0, "tamper" : 0, "battery_ok" : 1, "heartbeat" : 0, "mic" : "CRC", "mod" : "ASK", "freq" : 345.067, "rssi" : -0.100, "snr" : 11.020, "noise" : -11.120}
{"time" : "2023-02-01 11:39:09.417159", "model" : "Honeywell-Security", "id" : 952xxx, "channel" : 8, "event" : 0, "state" : "closed", "contact_open" : 0, "reed_open" : 0, "alarm" : 0, "tamper" : 0, "battery_ok" : 1, "heartbeat" : 0, "mic" : "CRC", "mod" : "ASK", "freq" : 345.066, "rssi" : -0.131, "snr" : 10.138, "noise" : -10.269}
{"time" : "2023-02-01 12:51:04.280162", "model" : "Honeywell-Security", "id" : 952xxx, "channel" : 8, "event" : 4, "state" : "closed", "contact_open" : 0, "reed_open" : 0, "alarm" : 0, "tamper" : 0, "battery_ok" : 1, "heartbeat" : 1, "mic" : "CRC", "mod" : "ASK", "freq" : 345.068, "rssi" : -0.100, "snr" : 10.731, "noise" : -10.831}
```

I don't have a Honeywell panel (yet), but I am using a bunch of the 5800 series and Versa sensors.  The 5800mini, 5800PIR-*, seem to work well.  The slim 5820L is currently problematic  The 5816 is ok as long as it isn't too close to the RTL-SDR.

**Comment by sheyman1** [comment]
OK, I just ran the requested test and here is the log.  I opened 4 devices and left them open without tripping any motion sensors.  None of the 4 were physically closed until after the log was downloaded so any closures seen are flapping.  You will probably see motion sensors tripping at the end as I walked back to my pc to download the log.

[home-assistant_2023-02-02T01-35-54.815Z.log](https://github.com/ufodone/envisalink_new/files/10564003/home-assistant_2023-02-02T01-35-54.815Z.log)

**Comment by ufodone** [comment]
@sheyman1 I have posted a [beta](https://github.com/ufodone/envisalink_new/releases/tag/v0.6.0-beta) release with the new algorithm from @philh30.  When you get a chance, please give it a try to see if it addresses your flapping issues and that there are no other side effects.

Be sure to set your `zonedump_interval` to 0 to disable them as they are no longer needed and will interfere if they are turned on.

You will need to enable the "Show Beta Versions" slider on the integration in order to see the release (labelled 0.6.0-beta).

**Comment by sheyman1** [comment]
Sorry for the silly question, but I don't see anywhere to "Show Beta
Versions"?

**Comment by sheyman1** [comment]
GENIUS!!!

Not sure what you all did but flapping has virtually stopped from what I can tell.  I opened about 5 doors / windows and no flapping, even with motion sensors being tripped.  I left all open for about 10-15 minutes and didn't see any flapping at all.  I've attached 2 logs, 1 with all 5 points still open and 1 after I closed all points.

When I opened the 6th window I did get one flap.

Observation:  With nothing faulted, if a motion is tripped it reports closure very quickly.  I walked thru my house with all doors and windows shut, just walking thru 3 different motion sensors and they report detected / not detected very quickly so after no motion detected they close within a few seconds at most.  If I open 1 window then do the same walk the motion sensors take about 30 seconds of no motion to show not detected.  With 2 windows open about 35 seconds for the motion to clear.  3 windows open still about 40 seconds.  4 windows about 50 seconds. 5 windows about 60 seconds.  6 windows about 70 seconds.

When 6 windows are open and I close one it takes about 45 seconds to show closed.  5th window closing about 45 seconds to show.  4th closing was fairly quick.  3rd closing about 25 seconds.  2nd closing about 15 seconds.  Closing last window is 1 second. 

The 3rd log is the entire test from start of opening to all closed.  Hope this helps, I'm thrilled that the flapping is so much better.  Thanks for all your work on this, if you need me to try anything else please let me know.

Scott
[home-assistant_2023-02-14T18-18-23.672Z.log](https://github.com/ufodone/envisalink_new/files/10735906/home-assistant_2023-02-14T18-18-23.672Z.log)
[home-assistant_2023-02-14T18-55-27.524Z.log](https://github.com/ufodone/envisalink_new/files/10735907/home-assistant_2023-02-14T18-55-27.524Z.log)
[home-assistant_2023-02-14T18-16-12.546Z.log](https://github.com/ufodone/envisalink_new/files/10735908/home-assistant_2023-02-14T18-16-12.546Z.log)

**Comment by ufodone** [comment]
Glad it's working better!  I think the behaviour you described is pretty consistent with how I'd expect it to work.  The only way to tell whether a zone is closed is to wait until it no longer shows up on the keypad updates.  Those updates come about every 5 seconds and cycles through each faulted zone one at a time while also potentially being interrupted by faults on motion zones, etc.  So the more zones you have open, the longer it's going to take to cycle through all of them such that the code can detect that a zone is no longer in the list.

@philh30 Is this all aligns with your expectations, I'll promote the change into a proper release and ask some other folks to test it out.  Thanks again for these changes!

**Comment by philh30** [comment]
It does line up perfectly with what I intended. I'd like to get cleared zones marked as closed faster without causing the closed zones to flutter, and I have a few ideas, but this is a pretty good balance to start with.

@sheyman1 One thing you should think about is shifting your motions to partition 2, assuming you're not already using partition 2 for another purpose. Each partition has its own queue of zone updates that don't interfere with each other, so your partition 2 motions would clear immediately even if you have 10 windows open on partition 1, and the motions wouldn't cause your partition 1 zones to flutter. Plus, when you arm stay partition 1 your partition 2 motions would continue reporting activity. You'd probably want to program HA to arm 2 when you arm 1 in away status. Both partitions alarm using the connected siren, though an individual keypad only chimes or alarms for the partition its assigned to.

@ufodone I did find a bug while testing what happens when tripping the alarm. The panel sends `EA` in the user code field when in alarm status, so the line below needs to trap for a non-integer or it errors out and starts a disconnect cycle. I'd like to get this fixed before sending out for broader testing. I may have time tomorrow to look at it if you don't get to it first.

https://github.com/ufodone/envisalink_new/blob/7e8363f9681263b6257e599e9ce53226726ac70a/custom_components/envisalink_new/pyenvisalink/honeywell_client.py#L193

**Comment by rct** [comment]
philh30 wrote:
> One thing you should think about is shifting your motions to partition 2, assuming you're not already using partition 2 for another purpose. Each partition has its own queue of zone updates that don't interfere with each other, so your partition 2 motions would clear immediately [...]

@philh30 - this sounds like good Honeywell configuration advice - Would you need to add a keypad to partition 2 or will the Envisalink be sufficient?

**Comment by philh30** [comment]
A second keypad is probably ideal if you're frequently arming both partitions, but I only have one and manage just fine. The Envisalink sees both, provided you've set up addresses for it on each. The Honeywell keypads only interact with their assigned partition, but you can pretty quickly swap a keypad to partition 2 by entering your PIN and then *2, so there's a failsafe for local control without the second keypad.

The Vista 20 also has a third partition, but it's intended for a shared lobby and arms based on the status of the other two. I haven't played with it. Not sure if it has any value or if the shared lobby logic makes it tricky to use.

**Comment by ufodone** [comment]
@philh30 I published a new beta release with a fix for the issue you mentioned.  I tested it with my mock server but let me know if it works for you as well.

**Comment by philh30** [comment]
The fix looks good

**Comment by ufodone** [comment]
> When both flags.not_used2 and flags.not_used3 are set it indicates a partition status update not related to a specific zone (battery flag in that case indicates the system battery instead of a zone battery). When those aren't set, the system could be reporting that it's counting down to arm (requires parsing the alpha field to verify). 

@philh30 Do the Honeywell panels support other languages?  A brief search indicated that maybe they do which means that the alpha parsing in your code would likely break for non-English panels.  But after looking at your code a bit more, I'm also wondering if the alpha parsing is even necessary?  

If I understand correct, when `not_used2` and `not_used3` are not set then the keypad update either indicates a zone update or that it's counting down to arm.  But rather than parsing the alpha field, couldn't you differentiate the two cases based on whether any of the `armed_*` flags are set?  E.g. if `armed_away` or `armed_stay` are set then the user field would be the countdown timer.  If they aren't set then it indicates a zone?

**Comment by philh30** [comment]
I'm not aware of a setting to change languages, and a quick check of the programming manuals that I have saved isn't turning one up. It's possible that there's an EVL-compatible version of the Honeywell panel that does support them though. A quick search shows a Spanish language keypad, but that just makes me think that the keypad is doing the translation while the panel continues to send out the memo field in English.

It's possible that logic would work... The only state I can think of where `armed_*` would be set while the number is indicating the zone would be when the alarm is tripped, though the `alarm` flag distinguishes those. I can try to work on that and do some testing. I'm still slammed at work so the soonest I'll be able to look at anything will be late this week.
