### ISSUE TITLE
Re-organize sensors on the device page

### ISSUE THREAD

**Issue by bdf0506** [ufodone/envisalink_new#90]
With the latest changes, we've exposed more attributes of the panel as entities, which is great. What isn't great is that it clutters up the device screen, and we now mix alarm sensors and alarm entities. While it does seem like there is some sort of logical order, I think we should break up the alarm panel sensors themselves from the zone sensors.

I'm thinking that any binary sensor relating to a zone stays in the *Sensor* section, and then anything related to the alarm panel itself, like Keypad, AC power, etc, moves to the *Diagnostic* section.

**Comment by ufodone** [comment]
In release [v0.8.2](https://github.com/ufodone/envisalink_new/releases/tag/v0.8.2).

I left the panel ready, alarm, and fire sensors where they were because they did not feel like diagnostics.
