### ISSUE TITLE
Missing icon?

### ISSUE THREAD

**Issue by chelming** [ufodone/envisalink_new#98]
Is the icon missing or did I do something wrong while installing it (0.8.2 from HACS)?
![image](https://github.com/ufodone/envisalink_new/assets/7746625/10a0cc60-cdd5-4fa9-b8d2-2c6c2c565dc8)

**Comment by ufodone** [comment]
It just hasn't been hooked up yet.  See the discussion [here](https://github.com/ufodone/envisalink_new/discussions/89).

**Comment by chelming** [comment]
dangit. I searched for "icon" and not logo. I swear I used the search.  closing as a dupe of #89.
